# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/facility/facility-monitoring-status.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v1/facility/facility-monitoring-status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,v1/facility/facility-monitoring-status.proto\x12&systems.ajax.mobilegw.grpc.v1.facility*\x80\x02\n\x10MonitoringStatus\x12!\n\x1dMONITORING_STATUS_UNSPECIFIED\x10\x00\x12#\n\x1fMONITORING_STATUS_ON_MONITORING\x10\x01\x12,\n(MONITORING_STATUS_ON_MULTIPLE_MONITORING\x10\x02\x12,\n(MONITORING_STATUS_REQUEST_FROM_INSTALLER\x10\x03\x12#\n\x1fMONITORING_STATUS_NO_MONITORING\x10\x04\x12#\n\x1fMONITORING_STATUS_IN_SLEEP_MODE\x10\x05\x42-\n&systems.ajax.mobilegw.grpc.v1.facilityP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.facility.facility_monitoring_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n&systems.ajax.mobilegw.grpc.v1.facilityP\001\272\002\000'
  _globals['_MONITORINGSTATUS']._serialized_start=89
  _globals['_MONITORINGSTATUS']._serialized_end=345
# @@protoc_insertion_point(module_scope)
