# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/mobile/v2/common/video/privacy/request_video_access_available_actions.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/mobile/v2/common/video/privacy/request_video_access_available_actions.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.mobile.v2.common.video.privacy import channel_permission_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_common_dot_video_dot_privacy_dot_channel__permission__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\\systems/ajax/api/mobile/v2/common/video/privacy/request_video_access_available_actions.proto\x12/systems.ajax.api.mobile.v2.common.video.privacy\x1aHsystems/ajax/api/mobile/v2/common/video/privacy/channel_permission.proto\"\xb1\x01\n\"RequestVideoAccessAvailableActions\x12 \n\x18\x63\x61n_request_video_access\x18\x01 \x01(\x08\x12i\n\x1d\x61vailable_channel_permissions\x18\x02 \x03(\x0e\x32\x42.systems.ajax.api.mobile.v2.common.video.privacy.ChannelPermissionB\x05P\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.mobile.v2.common.video.privacy.request_video_access_available_actions_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001\272\002\000'
  _globals['_REQUESTVIDEOACCESSAVAILABLEACTIONS']._serialized_start=220
  _globals['_REQUESTVIDEOACCESSAVAILABLEACTIONS']._serialized_end=397
# @@protoc_insertion_point(module_scope)
