# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/accounting/additional/data/additional_target_info.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/accounting/additional/data/additional_target_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.accounting.source.info import hub_info_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_communicationsvc_dot_mobile_dot_commonmodels_dot_notification_dot_accounting_dot_source_dot_info_dot_hub__info__pb2
from custom_components.ajax.systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.accounting.source.info import video_edge_info_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_communicationsvc_dot_mobile_dot_commonmodels_dot_notification_dot_accounting_dot_source_dot_info_dot_video__edge__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x87\x01systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/accounting/additional/data/additional_target_info.proto\x12jsystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.accounting.additional.data\x1ausystems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/accounting/source/info/hub_info.proto\x1a|systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/accounting/source/info/video_edge_info.proto\"\xc3\x02\n\x14\x41\x64\x64itionalTargetInfo\x12\x83\x01\n\x08hub_info\x18\x64 \x01(\x0b\x32o.systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.accounting.source.info.HubInfoH\x00\x12\x90\x01\n\x0fvideo_edge_info\x18\x65 \x01(\x0b\x32u.systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.accounting.source.info.VideoEdgeInfoH\x00\x42\x12\n\x10source_info_caseB{\njsystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.accounting.additional.dataP\x01\xba\x02\nAccountingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.accounting.additional.data.additional_target_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\njsystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.accounting.additional.dataP\001\272\002\nAccounting'
  _globals['_ADDITIONALTARGETINFO']._serialized_start=494
  _globals['_ADDITIONALTARGETINFO']._serialized_end=817
# @@protoc_insertion_point(module_scope)
