# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/accounting/additional/data/target_info.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/accounting/additional/data/target_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.logging.proto import formatting_options_pb2 as systems_dot_ajax_dot_logging_dot_proto_dot_formatting__options__pb2
from custom_components.ajax.systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.accounting.additional.data import additional_target_info_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_communicationsvc_dot_mobile_dot_commonmodels_dot_notification_dot_accounting_dot_additional_dot_data_dot_additional__target__info__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n|systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/accounting/additional/data/target_info.proto\x12jsystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.accounting.additional.data\x1a\x33systems/ajax/logging/proto/formatting_options.proto\x1a\x87\x01systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/accounting/additional/data/additional_target_info.proto\"\xee\x01\n\nTargetInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\x04name\x18\x02 \x01(\tB\x03\xf8\x44\x01\x12\x16\n\troom_name\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x9a\x01\n\x0f\x61\x64\x64itional_info\x18\x04 \x01(\x0b\x32\x80\x01.systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.accounting.additional.data.AdditionalTargetInfoB\x0c\n\n_room_nameB{\njsystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.accounting.additional.dataP\x01\xba\x02\nAccountingb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.accounting.additional.data.target_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\njsystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.accounting.additional.dataP\001\272\002\nAccounting'
  _globals['_TARGETINFO'].fields_by_name['name']._loaded_options = None
  _globals['_TARGETINFO'].fields_by_name['name']._serialized_options = b'\370D\001'
  _globals['_TARGETINFO']._serialized_start=428
  _globals['_TARGETINFO']._serialized_end=666
# @@protoc_insertion_point(module_scope)
