# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/device_command_photo_on_demand_mode/request.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/device_command_photo_on_demand_mode/request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nHv3/mobilegwsvc/service/device_command_photo_on_demand_mode/request.proto\x12Usystems.ajax.api.ecosystem.v3.mobilegwsvc.service.device_command_photo_on_demand_mode\"\xfd\x05\n%DeviceCommandPhotoOnDemandModeRequest\x12\x0e\n\x06hub_id\x18\x01 \x01(\t\x12\xb8\x01\n\x19photo_on_demand_mode_user\x18\x02 \x01(\x0e\x32\x92\x01.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.device_command_photo_on_demand_mode.DeviceCommandPhotoOnDemandModeRequest.PhotoOnDemandModeUserH\x00\x12\xc0\x01\n\x1dphoto_on_demand_mode_scenario\x18\x03 \x01(\x0e\x32\x96\x01.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.device_command_photo_on_demand_mode.DeviceCommandPhotoOnDemandModeRequest.PhotoOnDemandModeScenarioH\x00\"\x8f\x01\n\x15PhotoOnDemandModeUser\x12)\n%PHOTO_ON_DEMAND_MODE_USER_UNSPECIFIED\x10\x00\x12%\n!PHOTO_ON_DEMAND_MODE_USER_DISABLE\x10\x01\x12$\n PHOTO_ON_DEMAND_MODE_USER_ENABLE\x10\x02\"\x9f\x01\n\x19PhotoOnDemandModeScenario\x12-\n)PHOTO_ON_DEMAND_MODE_SCENARIO_UNSPECIFIED\x10\x00\x12)\n%PHOTO_ON_DEMAND_MODE_SCENARIO_DISABLE\x10\x01\x12(\n$PHOTO_ON_DEMAND_MODE_SCENARIO_ENABLE\x10\x02\x42\x12\n\x10\x61\x64\x64itional_paramB\x05P\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.device_command_photo_on_demand_mode.request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001\272\002\000'
  _globals['_DEVICECOMMANDPHOTOONDEMANDMODEREQUEST']._serialized_start=164
  _globals['_DEVICECOMMANDPHOTOONDEMANDMODEREQUEST']._serialized_end=929
  _globals['_DEVICECOMMANDPHOTOONDEMANDMODEREQUEST_PHOTOONDEMANDMODEUSER']._serialized_start=604
  _globals['_DEVICECOMMANDPHOTOONDEMANDMODEREQUEST_PHOTOONDEMANDMODEUSER']._serialized_end=747
  _globals['_DEVICECOMMANDPHOTOONDEMANDMODEREQUEST_PHOTOONDEMANDMODESCENARIO']._serialized_start=750
  _globals['_DEVICECOMMANDPHOTOONDEMANDMODEREQUEST_PHOTOONDEMANDMODESCENARIO']._serialized_end=909
# @@protoc_insertion_point(module_scope)
