# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/mobile/v2/space/group/space_group_endpoints.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/mobile/v2/space/group/space_group_endpoints.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.mobile.v2.space.group import assign_devices_to_group_request_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_group_dot_assign__devices__to__group__request__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.space.group import create_group_request_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_group_dot_create__group__request__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.space.group import delete_group_request_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_group_dot_delete__group__request__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.space.group import update_group_request_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_group_dot_update__group__request__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBsystems/ajax/api/mobile/v2/space/group/space_group_endpoints.proto\x12&systems.ajax.api.mobile.v2.space.group\x1aLsystems/ajax/api/mobile/v2/space/group/assign_devices_to_group_request.proto\x1a\x41systems/ajax/api/mobile/v2/space/group/create_group_request.proto\x1a\x41systems/ajax/api/mobile/v2/space/group/delete_group_request.proto\x1a\x41systems/ajax/api/mobile/v2/space/group/update_group_request.proto2\xc3\x04\n\x11SpaceGroupService\x12\x81\x01\n\x06\x63reate\x12:.systems.ajax.api.mobile.v2.space.group.CreateGroupRequest\x1a;.systems.ajax.api.mobile.v2.space.group.CreateGroupResponse\x12\x81\x01\n\x06update\x12:.systems.ajax.api.mobile.v2.space.group.UpdateGroupRequest\x1a;.systems.ajax.api.mobile.v2.space.group.UpdateGroupResponse\x12\x81\x01\n\x06\x64\x65lete\x12:.systems.ajax.api.mobile.v2.space.group.DeleteGroupRequest\x1a;.systems.ajax.api.mobile.v2.space.group.DeleteGroupResponse\x12\xa1\x01\n\x14\x61ssignDevicesToGroup\x12\x43.systems.ajax.api.mobile.v2.space.group.AssignDevicesToGroupRequest\x1a\x44.systems.ajax.api.mobile.v2.space.group.AssignDevicesToGroupResponseB\x05P\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.mobile.v2.space.group.space_group_endpoints_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001\272\002\000'
  _globals['_SPACEGROUPSERVICE']._serialized_start=390
  _globals['_SPACEGROUPSERVICE']._serialized_end=969
# @@protoc_insertion_point(module_scope)
