# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/update_account_profile/response.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/update_account_profile/response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.v3.mobilegwsvc.commonmodels.account import account_pb2 as v3_dot_mobilegwsvc_dot_commonmodels_dot_account_dot_account__pb2
from custom_components.ajax.v3.mobilegwsvc.commonmodels.response import response_pb2 as v3_dot_mobilegwsvc_dot_commonmodels_dot_response_dot_response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<v3/mobilegwsvc/service/update_account_profile/response.proto\x12Hsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.update_account_profile\x1a\x31v3/mobilegwsvc/commonmodels/account/account.proto\x1a\x33v3/mobilegwsvc/commonmodels/response/response.proto\"\xf6\x03\n\x1cUpdateAccountProfileResponse\x12\x81\x01\n\x07success\x18\x01 \x01(\x0b\x32n.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.update_account_profile.UpdateAccountProfileResponse.SuccessH\x00\x12\x81\x01\n\x07\x66\x61ilure\x18\x02 \x01(\x0b\x32n.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.update_account_profile.UpdateAccountProfileResponse.FailureH\x00\x1a\x63\n\x07Success\x12X\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0b\x32G.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.account.Account\x1a]\n\x07\x46\x61ilure\x12R\n\x0b\x62\x61\x64_request\x18\x01 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.ErrorB\n\n\x08responseBT\nMsystems.ajax.api.ecosystem.v3.mobilegwsvc.user.service.update_account_profileP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.update_account_profile.response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nMsystems.ajax.api.ecosystem.v3.mobilegwsvc.user.service.update_account_profileP\001\272\002\000'
  _globals['_UPDATEACCOUNTPROFILERESPONSE']._serialized_start=243
  _globals['_UPDATEACCOUNTPROFILERESPONSE']._serialized_end=745
  _globals['_UPDATEACCOUNTPROFILERESPONSE_SUCCESS']._serialized_start=539
  _globals['_UPDATEACCOUNTPROFILERESPONSE_SUCCESS']._serialized_end=638
  _globals['_UPDATEACCOUNTPROFILERESPONSE_FAILURE']._serialized_start=640
  _globals['_UPDATEACCOUNTPROFILERESPONSE_FAILURE']._serialized_end=733
# @@protoc_insertion_point(module_scope)
