# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/find_video_edge_firmware_release_notes/response.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/find_video_edge_firmware_release_notes/response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.v3.mobilegwsvc.commonmodels.response import response_pb2 as v3_dot_mobilegwsvc_dot_commonmodels_dot_response_dot_response__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.common.video.videoedge.firmware import release_notes_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_common_dot_video_dot_videoedge_dot_firmware_dot_release__notes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nLv3/mobilegwsvc/service/find_video_edge_firmware_release_notes/response.proto\x12Xsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.find_video_edge_firmware_release_notes\x1a\x33v3/mobilegwsvc/commonmodels/response/response.proto\x1aNsystems/ajax/api/mobile/v2/common/video/videoedge/firmware/release_notes.proto\"\xb3\x05\n)FindVideoEdgeFirmwareReleaseNotesResponse\x12\x9f\x01\n\x07success\x18\x01 \x01(\x0b\x32\x8b\x01.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.find_video_edge_firmware_release_notes.FindVideoEdgeFirmwareReleaseNotesResponse.SuccessH\x00\x12\x9f\x01\n\x07\x66\x61ilure\x18\x02 \x01(\x0b\x32\x8b\x01.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.find_video_edge_firmware_release_notes.FindVideoEdgeFirmwareReleaseNotesResponse.FailureH\x00\x1aj\n\x07Success\x12_\n\rrelease_notes\x18\x01 \x01(\x0b\x32H.systems.ajax.api.mobile.v2.common.video.videoedge.firmware.ReleaseNotes\x1a\xc9\x01\n\x07\x46\x61ilure\x12T\n\x0b\x62\x61\x64_request\x18\x01 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.ErrorH\x00\x12_\n\x12\x66irmware_not_found\x18\x02 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.ErrorB\x02\x18\x01H\x00\x42\x07\n\x05\x65rrorB\n\n\x08responseB_\nXsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.find_video_edge_firmware_release_notesP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.find_video_edge_firmware_release_notes.response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nXsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.find_video_edge_firmware_release_notesP\001\272\002\000'
  _globals['_FINDVIDEOEDGEFIRMWARERELEASENOTESRESPONSE_FAILURE'].fields_by_name['firmware_not_found']._loaded_options = None
  _globals['_FINDVIDEOEDGEFIRMWARERELEASENOTESRESPONSE_FAILURE'].fields_by_name['firmware_not_found']._serialized_options = b'\030\001'
  _globals['_FINDVIDEOEDGEFIRMWARERELEASENOTESRESPONSE']._serialized_start=304
  _globals['_FINDVIDEOEDGEFIRMWARERELEASENOTESRESPONSE']._serialized_end=995
  _globals['_FINDVIDEOEDGEFIRMWARERELEASENOTESRESPONSE_SUCCESS']._serialized_start=673
  _globals['_FINDVIDEOEDGEFIRMWARERELEASENOTESRESPONSE_SUCCESS']._serialized_end=779
  _globals['_FINDVIDEOEDGEFIRMWARERELEASENOTESRESPONSE_FAILURE']._serialized_start=782
  _globals['_FINDVIDEOEDGEFIRMWARERELEASENOTESRESPONSE_FAILURE']._serialized_end=983
# @@protoc_insertion_point(module_scope)
