# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/set_max_video_cloud_archive_depth/endpoint.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/set_max_video_cloud_archive_depth/endpoint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.v3.mobilegwsvc.service.set_max_video_cloud_archive_depth import request_pb2 as v3_dot_mobilegwsvc_dot_service_dot_set__max__video__cloud__archive__depth_dot_request__pb2
from custom_components.ajax.v3.mobilegwsvc.service.set_max_video_cloud_archive_depth import response_pb2 as v3_dot_mobilegwsvc_dot_service_dot_set__max__video__cloud__archive__depth_dot_response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nGv3/mobilegwsvc/service/set_max_video_cloud_archive_depth/endpoint.proto\x12Ssystems.ajax.api.ecosystem.v3.mobilegwsvc.service.set_max_video_cloud_archive_depth\x1a\x46v3/mobilegwsvc/service/set_max_video_cloud_archive_depth/request.proto\x1aGv3/mobilegwsvc/service/set_max_video_cloud_archive_depth/response.proto2\xa6\x02\n#SetMaxVideoCloudArchiveDepthService\x12\xfe\x01\n\x07\x65xecute\x12x.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.set_max_video_cloud_archive_depth.SetMaxVideoCloudArchiveDepthRequest\x1ay.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.set_max_video_cloud_archive_depth.SetMaxVideoCloudArchiveDepthResponseBZ\nSsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.set_max_video_cloud_archive_depthP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.set_max_video_cloud_archive_depth.endpoint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nSsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.set_max_video_cloud_archive_depthP\001\272\002\000'
  _globals['_SETMAXVIDEOCLOUDARCHIVEDEPTHSERVICE']._serialized_start=306
  _globals['_SETMAXVIDEOCLOUDARCHIVEDEPTHSERVICE']._serialized_end=600
# @@protoc_insertion_point(module_scope)
