# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/mobile/v2/common/video/videoedge/onvif/onvif_info.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/mobile/v2/common/video/videoedge/onvif/onvif_info.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nHsystems/ajax/api/mobile/v2/common/video/videoedge/onvif/onvif_info.proto\x12\x37systems.ajax.api.mobile.v2.common.video.videoedge.onvif\"&\n\tOnvifInfo\x12\x19\n\x11user_auth_enabled\x18\x01 \x01(\x08\x42\x05P\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.mobile.v2.common.video.videoedge.onvif.onvif_info_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001\272\002\000'
  _globals['_ONVIFINFO']._serialized_start=133
  _globals['_ONVIFINFO']._serialized_end=171
# @@protoc_insertion_point(module_scope)
