# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from custom_components.ajax.v1.auth import login_response_pb2 as v1_dot_auth_dot_login__response__pb2
from custom_components.ajax.v1.auth import switch_context_request_pb2 as v1_dot_auth_dot_switch__context__request__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in v1/auth/context_service_endpoints_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContextServiceStub(object):
    """
    Service that provides methods for mobile users switch context between companies and personal account.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.switchCompanyContext = channel.unary_unary(
                '/systems.ajax.mobilegw.grpc.v1.auth.ContextService/switchCompanyContext',
                request_serializer=v1_dot_auth_dot_switch__context__request__pb2.SwitchContextRequest.SerializeToString,
                response_deserializer=v1_dot_auth_dot_login__response__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.switchContextToPersonalAccount = channel.unary_unary(
                '/systems.ajax.mobilegw.grpc.v1.auth.ContextService/switchContextToPersonalAccount',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=v1_dot_auth_dot_login__response__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.getCurrentContext = channel.unary_unary(
                '/systems.ajax.mobilegw.grpc.v1.auth.ContextService/getCurrentContext',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=v1_dot_auth_dot_login__response__pb2.LoginResponse.FromString,
                _registered_method=True)


class ContextServiceServicer(object):
    """
    Service that provides methods for mobile users switch context between companies and personal account.
    """

    def switchCompanyContext(self, request, context):
        """
        Possible error statuses and corresponding error templates

        TIMEOUT - systems.ajax.mobilegw.error.timeout
        UNAUTHENTICATED = "systems.ajax.mobilegw.error.unauthenticated"
        INTERNAL_SERVICE_ERROR = "systems.ajax.mobilegw.error.internalServiceError"
        NOT_FOUND= "systems.ajax.mobilegw.error.notFound.user"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def switchContextToPersonalAccount(self, request, context):
        """
        Possible error statuses and corresponding error templates

        TIMEOUT - systems.ajax.mobilegw.error.timeout
        UNAUTHENTICATED = "systems.ajax.mobilegw.error.unauthenticated"
        INTERNAL_SERVICE_ERROR = "systems.ajax.mobilegw.error.internalServiceError"
        NOT_FOUND= "systems.ajax.mobilegw.error.notFound.user"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getCurrentContext(self, request, context):
        """
        Possible error statuses and corresponding error templates

        TIMEOUT - systems.ajax.mobilegw.error.timeout
        UNAUTHENTICATED = "systems.ajax.mobilegw.error.unauthenticated"
        INTERNAL_SERVICE_ERROR = "systems.ajax.mobilegw.error.internalServiceError"
        NOT_FOUND= "systems.ajax.mobilegw.error.notFound.user"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContextServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'switchCompanyContext': grpc.unary_unary_rpc_method_handler(
                    servicer.switchCompanyContext,
                    request_deserializer=v1_dot_auth_dot_switch__context__request__pb2.SwitchContextRequest.FromString,
                    response_serializer=v1_dot_auth_dot_login__response__pb2.LoginResponse.SerializeToString,
            ),
            'switchContextToPersonalAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.switchContextToPersonalAccount,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=v1_dot_auth_dot_login__response__pb2.LoginResponse.SerializeToString,
            ),
            'getCurrentContext': grpc.unary_unary_rpc_method_handler(
                    servicer.getCurrentContext,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=v1_dot_auth_dot_login__response__pb2.LoginResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systems.ajax.mobilegw.grpc.v1.auth.ContextService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('systems.ajax.mobilegw.grpc.v1.auth.ContextService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContextService(object):
    """
    Service that provides methods for mobile users switch context between companies and personal account.
    """

    @staticmethod
    def switchCompanyContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/systems.ajax.mobilegw.grpc.v1.auth.ContextService/switchCompanyContext',
            v1_dot_auth_dot_switch__context__request__pb2.SwitchContextRequest.SerializeToString,
            v1_dot_auth_dot_login__response__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def switchContextToPersonalAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/systems.ajax.mobilegw.grpc.v1.auth.ContextService/switchContextToPersonalAccount',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            v1_dot_auth_dot_login__response__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getCurrentContext(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/systems.ajax.mobilegw.grpc.v1.auth.ContextService/getCurrentContext',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            v1_dot_auth_dot_login__response__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
