# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/protobuf/hub/device/combi_protect.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/protobuf/hub/device/combi_protect.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from custom_components.ajax.systems.ajax.protobuf.hub.device import common_device_pb2 as systems_dot_ajax_dot_protobuf_dot_hub_dot_device_dot_common__device__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n4systems/ajax/protobuf/hub/device/combi_protect.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x34systems/ajax/protobuf/hub/device/common_device.proto\"\xab\x04\n\x0c\x43ombiProtect\x12\'\n\x0b\x63ommon_part\x18\xe8\x07 \x01(\x0b\x32\x11.CommonDevicePart\x12\x32\n\x0esiren_triggers\x18. \x03(\x0e\x32\x1a.CombiProtect.SirenTrigger\x12\x1b\n\x13motion_sensor_aware\x18\x31 \x01(\x08\x12 \n\x18glass_break_sensor_aware\x18\x32 \x01(\x08\x12\x1a\n\x12motion_sensitivity\x18\x33 \x01(\x05\x12\x1f\n\x17glass_break_sensitivity\x18\x34 \x01(\x05\x12#\n\x1bmotion_sensor_always_active\x18\x35 \x01(\x08\x12(\n glass_break_sensor_always_active\x18\x36 \x01(\x08\x12\x33\n\x0fmotion_detected\x18\x37 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x38\n\x14glass_break_detected\x18\x38 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\'\n\x07subtype\x18\xc3\x01 \x01(\x0e\x32\x15.CombiProtect.Subtype\"@\n\x0cSirenTrigger\x12\x19\n\x15NO_SIREN_TRIGGER_INFO\x10\x00\x12\n\n\x06MOTION\x10\x01\x12\t\n\x05GLASS\x10\x02\"\x19\n\x07Subtype\x12\x0e\n\nNO_SUBTYPE\x10\x00\x42.\n systems.ajax.protobuf.hub.deviceP\x01\xba\x02\x07Systemsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.protobuf.hub.device.combi_protect_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n systems.ajax.protobuf.hub.deviceP\001\272\002\007Systems'
  _globals['_COMBIPROTECT']._serialized_start=143
  _globals['_COMBIPROTECT']._serialized_end=698
  _globals['_COMBIPROTECT_SIRENTRIGGER']._serialized_start=607
  _globals['_COMBIPROTECT_SIRENTRIGGER']._serialized_end=671
  _globals['_COMBIPROTECT_SUBTYPE']._serialized_start=673
  _globals['_COMBIPROTECT_SUBTYPE']._serialized_end=698
# @@protoc_insertion_point(module_scope)
