# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/protobuf/hub/device/keypad.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/protobuf/hub/device/keypad.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from custom_components.ajax.systems.ajax.protobuf.hub.device import common_device_pb2 as systems_dot_ajax_dot_protobuf_dot_hub_dot_device_dot_common__device__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-systems/ajax/protobuf/hub/device/keypad.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x34systems/ajax/protobuf/hub/device/common_device.proto\"\xe9\x06\n\x06Keypad\x12\'\n\x0b\x63ommon_part\x18\xe8\x07 \x01(\x0b\x32\x11.CommonDevicePart\x12,\n\x0esiren_triggers\x18. \x03(\x0e\x32\x14.Keypad.SirenTrigger\x12.\n\x0f\x61\x63\x63\x65ss_profiles\x18> \x03(\x0e\x32\x15.Keypad.AccessProfile\x12\x38\n\x14star_button_function\x18\x38 \x01(\x0e\x32\x1a.Keypad.StarButtonFunction\x12\x10\n\x08password\x18\x31 \x01(\t\x12\x1d\n\x15\x66orce_disarm_password\x18\x33 \x01(\t\x12+\n#block_on_multiple_password_failures\x18\x36 \x01(\x08\x12;\n3time_to_block_on_multiple_password_failures_minutes\x18\x34 \x01(\x05\x12+\n\x07\x62locked\x18\x37 \x01(\x0b\x32\x1a.google.protobuf.BoolValue\x12\x19\n\x11\x61llow_fast_arming\x18\x35 \x01(\x08\x12\x18\n\x10\x62rightness_level\x18; \x01(\x05\x12\x14\n\x0cvolume_level\x18< \x01(\x05\x12\x1b\n\x13\x61ssociated_group_id\x18= \x01(\t\x12\x15\n\rpassword_hash\x18J \x01(\t\x12\x1c\n\x14password_hash_duress\x18K \x01(\t\x12!\n\x07subtype\x18\xc3\x01 \x01(\x0e\x32\x0f.Keypad.Subtype\">\n\x0cSirenTrigger\x12\x19\n\x15NO_SIREN_TRIGGER_INFO\x10\x00\x12\x13\n\x0fSECURITY_BUTTON\x10\x01\"d\n\x12StarButtonFunction\x12 \n\x1cNO_STAR_BUTTON_FUNCTION_INFO\x10\x00\x12\x0c\n\x08\x44ISABLED\x10\x01\x12\t\n\x05PANIC\x10\x02\x12\x13\n\x0fMUTE_FIRE_ALARM\x10\x03\"U\n\rAccessProfile\x12\x1a\n\x16NO_ACCESS_PROFILE_INFO\x10\x00\x12\x15\n\x11KEYBOARD_PASSWORD\x10\x01\x12\x11\n\rUSER_PASSWORD\x10\x02\"\x19\n\x07Subtype\x12\x0e\n\nNO_SUBTYPE\x10\x00\x42.\n systems.ajax.protobuf.hub.deviceP\x01\xba\x02\x07Systemsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.protobuf.hub.device.keypad_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n systems.ajax.protobuf.hub.deviceP\001\272\002\007Systems'
  _globals['_KEYPAD']._serialized_start=136
  _globals['_KEYPAD']._serialized_end=1009
  _globals['_KEYPAD_SIRENTRIGGER']._serialized_start=731
  _globals['_KEYPAD_SIRENTRIGGER']._serialized_end=793
  _globals['_KEYPAD_STARBUTTONFUNCTION']._serialized_start=795
  _globals['_KEYPAD_STARBUTTONFUNCTION']._serialized_end=895
  _globals['_KEYPAD_ACCESSPROFILE']._serialized_start=897
  _globals['_KEYPAD_ACCESSPROFILE']._serialized_end=982
  _globals['_KEYPAD_SUBTYPE']._serialized_start=984
  _globals['_KEYPAD_SUBTYPE']._serialized_end=1009
# @@protoc_insertion_point(module_scope)
