# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/protobuf/hub/device/multi_transmitter.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/protobuf/hub/device/multi_transmitter.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
from custom_components.ajax.systems.ajax.protobuf.hub.device import common_device_pb2 as systems_dot_ajax_dot_protobuf_dot_hub_dot_device_dot_common__device__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n8systems/ajax/protobuf/hub/device/multi_transmitter.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x34systems/ajax/protobuf/hub/device/common_device.proto\"\x97\x03\n\x10MultiTransmitter\x12\'\n\x0b\x63ommon_part\x18\xe8\x07 \x01(\x0b\x32\x11.CommonDevicePart\x12\x16\n\x0e\x65xternal_power\x18\x31 \x01(\x08\x12$\n\x1c\x65xternal_sensor_power_broken\x18\x33 \x01(\x08\x12\x18\n\x10\x62\x61ttery_charging\x18\x34 \x01(\x08\x12\x16\n\x0e\x62\x61ttery_broken\x18\x35 \x01(\x08\x12,\n$external_fire_notifiers_power_broken\x18\x37 \x01(\x08\x12\x36\n\x0esiren_triggers\x18. \x03(\x0e\x32\x1e.MultiTransmitter.SirenTrigger\x12+\n\x07subtype\x18\xc3\x01 \x01(\x0e\x32\x19.MultiTransmitter.Subtype\"<\n\x0cSirenTrigger\x12\x19\n\x15NO_SIREN_TRIGGER_INFO\x10\x00\x12\x11\n\rSHORT_CIRCUIT\x10\x01\"\x19\n\x07Subtype\x12\x0e\n\nNO_SUBTYPE\x10\x00\x42.\n systems.ajax.protobuf.hub.deviceP\x01\xba\x02\x07Systemsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.protobuf.hub.device.multi_transmitter_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n systems.ajax.protobuf.hub.deviceP\001\272\002\007Systems'
  _globals['_MULTITRANSMITTER']._serialized_start=147
  _globals['_MULTITRANSMITTER']._serialized_end=554
  _globals['_MULTITRANSMITTER_SIRENTRIGGER']._serialized_start=467
  _globals['_MULTITRANSMITTER_SIRENTRIGGER']._serialized_end=527
  _globals['_MULTITRANSMITTER_SUBTYPE']._serialized_start=529
  _globals['_MULTITRANSMITTER_SUBTYPE']._serialized_end=554
# @@protoc_insertion_point(module_scope)
