from systems.ajax.protobuf.hub.device import common_device_pb2 as _common_device_pb2
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from collections.abc import Iterable as _Iterable, Mapping as _Mapping
from typing import ClassVar as _ClassVar, Optional as _Optional, Union as _Union

DESCRIPTOR: _descriptor.FileDescriptor

class UniversalDevice(_message.Message):
    __slots__ = ("common_part", "device_debug_enabled", "settings", "statuses", "alarms", "subtype")
    class Setting(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        NO_SETTING_INFO: _ClassVar[UniversalDevice.Setting]
        SETTING_1: _ClassVar[UniversalDevice.Setting]
        SETTING_2: _ClassVar[UniversalDevice.Setting]
        SETTING_3: _ClassVar[UniversalDevice.Setting]
        SETTING_4: _ClassVar[UniversalDevice.Setting]
        SETTING_5: _ClassVar[UniversalDevice.Setting]
        SETTING_6: _ClassVar[UniversalDevice.Setting]
        SETTING_7: _ClassVar[UniversalDevice.Setting]
        SETTING_8: _ClassVar[UniversalDevice.Setting]
        SETTING_9: _ClassVar[UniversalDevice.Setting]
        SETTING_10: _ClassVar[UniversalDevice.Setting]
        SETTING_11: _ClassVar[UniversalDevice.Setting]
        SETTING_12: _ClassVar[UniversalDevice.Setting]
        SETTING_13: _ClassVar[UniversalDevice.Setting]
        SETTING_14: _ClassVar[UniversalDevice.Setting]
        SETTING_15: _ClassVar[UniversalDevice.Setting]
        SETTING_16: _ClassVar[UniversalDevice.Setting]
        SETTING_17: _ClassVar[UniversalDevice.Setting]
        SETTING_18: _ClassVar[UniversalDevice.Setting]
        SETTING_19: _ClassVar[UniversalDevice.Setting]
        SETTING_20: _ClassVar[UniversalDevice.Setting]
        SETTING_21: _ClassVar[UniversalDevice.Setting]
        SETTING_22: _ClassVar[UniversalDevice.Setting]
        SETTING_23: _ClassVar[UniversalDevice.Setting]
        SETTING_24: _ClassVar[UniversalDevice.Setting]
        SETTING_25: _ClassVar[UniversalDevice.Setting]
        SETTING_26: _ClassVar[UniversalDevice.Setting]
        SETTING_27: _ClassVar[UniversalDevice.Setting]
        SETTING_28: _ClassVar[UniversalDevice.Setting]
        SETTING_29: _ClassVar[UniversalDevice.Setting]
        SETTING_30: _ClassVar[UniversalDevice.Setting]
        SETTING_31: _ClassVar[UniversalDevice.Setting]
        SETTING_32: _ClassVar[UniversalDevice.Setting]
    NO_SETTING_INFO: UniversalDevice.Setting
    SETTING_1: UniversalDevice.Setting
    SETTING_2: UniversalDevice.Setting
    SETTING_3: UniversalDevice.Setting
    SETTING_4: UniversalDevice.Setting
    SETTING_5: UniversalDevice.Setting
    SETTING_6: UniversalDevice.Setting
    SETTING_7: UniversalDevice.Setting
    SETTING_8: UniversalDevice.Setting
    SETTING_9: UniversalDevice.Setting
    SETTING_10: UniversalDevice.Setting
    SETTING_11: UniversalDevice.Setting
    SETTING_12: UniversalDevice.Setting
    SETTING_13: UniversalDevice.Setting
    SETTING_14: UniversalDevice.Setting
    SETTING_15: UniversalDevice.Setting
    SETTING_16: UniversalDevice.Setting
    SETTING_17: UniversalDevice.Setting
    SETTING_18: UniversalDevice.Setting
    SETTING_19: UniversalDevice.Setting
    SETTING_20: UniversalDevice.Setting
    SETTING_21: UniversalDevice.Setting
    SETTING_22: UniversalDevice.Setting
    SETTING_23: UniversalDevice.Setting
    SETTING_24: UniversalDevice.Setting
    SETTING_25: UniversalDevice.Setting
    SETTING_26: UniversalDevice.Setting
    SETTING_27: UniversalDevice.Setting
    SETTING_28: UniversalDevice.Setting
    SETTING_29: UniversalDevice.Setting
    SETTING_30: UniversalDevice.Setting
    SETTING_31: UniversalDevice.Setting
    SETTING_32: UniversalDevice.Setting
    class Status(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        NO_STATUS_INFO: _ClassVar[UniversalDevice.Status]
        STATUS_1: _ClassVar[UniversalDevice.Status]
        STATUS_2: _ClassVar[UniversalDevice.Status]
        STATUS_3: _ClassVar[UniversalDevice.Status]
        STATUS_4: _ClassVar[UniversalDevice.Status]
        STATUS_5: _ClassVar[UniversalDevice.Status]
        STATUS_6: _ClassVar[UniversalDevice.Status]
        STATUS_7: _ClassVar[UniversalDevice.Status]
        STATUS_8: _ClassVar[UniversalDevice.Status]
        STATUS_9: _ClassVar[UniversalDevice.Status]
        STATUS_10: _ClassVar[UniversalDevice.Status]
        STATUS_11: _ClassVar[UniversalDevice.Status]
        STATUS_12: _ClassVar[UniversalDevice.Status]
        STATUS_13: _ClassVar[UniversalDevice.Status]
        STATUS_14: _ClassVar[UniversalDevice.Status]
        STATUS_15: _ClassVar[UniversalDevice.Status]
        STATUS_16: _ClassVar[UniversalDevice.Status]
        STATUS_17: _ClassVar[UniversalDevice.Status]
        STATUS_18: _ClassVar[UniversalDevice.Status]
        STATUS_19: _ClassVar[UniversalDevice.Status]
        STATUS_20: _ClassVar[UniversalDevice.Status]
        STATUS_21: _ClassVar[UniversalDevice.Status]
        STATUS_22: _ClassVar[UniversalDevice.Status]
        STATUS_23: _ClassVar[UniversalDevice.Status]
        STATUS_24: _ClassVar[UniversalDevice.Status]
        STATUS_25: _ClassVar[UniversalDevice.Status]
        STATUS_26: _ClassVar[UniversalDevice.Status]
        STATUS_27: _ClassVar[UniversalDevice.Status]
        STATUS_28: _ClassVar[UniversalDevice.Status]
        STATUS_29: _ClassVar[UniversalDevice.Status]
        STATUS_30: _ClassVar[UniversalDevice.Status]
        STATUS_31: _ClassVar[UniversalDevice.Status]
        STATUS_32: _ClassVar[UniversalDevice.Status]
    NO_STATUS_INFO: UniversalDevice.Status
    STATUS_1: UniversalDevice.Status
    STATUS_2: UniversalDevice.Status
    STATUS_3: UniversalDevice.Status
    STATUS_4: UniversalDevice.Status
    STATUS_5: UniversalDevice.Status
    STATUS_6: UniversalDevice.Status
    STATUS_7: UniversalDevice.Status
    STATUS_8: UniversalDevice.Status
    STATUS_9: UniversalDevice.Status
    STATUS_10: UniversalDevice.Status
    STATUS_11: UniversalDevice.Status
    STATUS_12: UniversalDevice.Status
    STATUS_13: UniversalDevice.Status
    STATUS_14: UniversalDevice.Status
    STATUS_15: UniversalDevice.Status
    STATUS_16: UniversalDevice.Status
    STATUS_17: UniversalDevice.Status
    STATUS_18: UniversalDevice.Status
    STATUS_19: UniversalDevice.Status
    STATUS_20: UniversalDevice.Status
    STATUS_21: UniversalDevice.Status
    STATUS_22: UniversalDevice.Status
    STATUS_23: UniversalDevice.Status
    STATUS_24: UniversalDevice.Status
    STATUS_25: UniversalDevice.Status
    STATUS_26: UniversalDevice.Status
    STATUS_27: UniversalDevice.Status
    STATUS_28: UniversalDevice.Status
    STATUS_29: UniversalDevice.Status
    STATUS_30: UniversalDevice.Status
    STATUS_31: UniversalDevice.Status
    STATUS_32: UniversalDevice.Status
    class Alarm(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        NO_ALARM_INFO: _ClassVar[UniversalDevice.Alarm]
        ALARM_1: _ClassVar[UniversalDevice.Alarm]
        ALARM_2: _ClassVar[UniversalDevice.Alarm]
        ALARM_3: _ClassVar[UniversalDevice.Alarm]
        ALARM_4: _ClassVar[UniversalDevice.Alarm]
        ALARM_5: _ClassVar[UniversalDevice.Alarm]
        ALARM_6: _ClassVar[UniversalDevice.Alarm]
        ALARM_7: _ClassVar[UniversalDevice.Alarm]
        ALARM_8: _ClassVar[UniversalDevice.Alarm]
        ALARM_9: _ClassVar[UniversalDevice.Alarm]
        ALARM_10: _ClassVar[UniversalDevice.Alarm]
        ALARM_11: _ClassVar[UniversalDevice.Alarm]
        ALARM_12: _ClassVar[UniversalDevice.Alarm]
        ALARM_13: _ClassVar[UniversalDevice.Alarm]
        ALARM_14: _ClassVar[UniversalDevice.Alarm]
        ALARM_15: _ClassVar[UniversalDevice.Alarm]
        ALARM_16: _ClassVar[UniversalDevice.Alarm]
        ALARM_17: _ClassVar[UniversalDevice.Alarm]
        ALARM_18: _ClassVar[UniversalDevice.Alarm]
        ALARM_19: _ClassVar[UniversalDevice.Alarm]
        ALARM_20: _ClassVar[UniversalDevice.Alarm]
        ALARM_21: _ClassVar[UniversalDevice.Alarm]
        ALARM_22: _ClassVar[UniversalDevice.Alarm]
        ALARM_23: _ClassVar[UniversalDevice.Alarm]
        ALARM_24: _ClassVar[UniversalDevice.Alarm]
        ALARM_25: _ClassVar[UniversalDevice.Alarm]
        ALARM_26: _ClassVar[UniversalDevice.Alarm]
        ALARM_27: _ClassVar[UniversalDevice.Alarm]
        ALARM_28: _ClassVar[UniversalDevice.Alarm]
        ALARM_29: _ClassVar[UniversalDevice.Alarm]
        ALARM_30: _ClassVar[UniversalDevice.Alarm]
        ALARM_31: _ClassVar[UniversalDevice.Alarm]
        ALARM_32: _ClassVar[UniversalDevice.Alarm]
    NO_ALARM_INFO: UniversalDevice.Alarm
    ALARM_1: UniversalDevice.Alarm
    ALARM_2: UniversalDevice.Alarm
    ALARM_3: UniversalDevice.Alarm
    ALARM_4: UniversalDevice.Alarm
    ALARM_5: UniversalDevice.Alarm
    ALARM_6: UniversalDevice.Alarm
    ALARM_7: UniversalDevice.Alarm
    ALARM_8: UniversalDevice.Alarm
    ALARM_9: UniversalDevice.Alarm
    ALARM_10: UniversalDevice.Alarm
    ALARM_11: UniversalDevice.Alarm
    ALARM_12: UniversalDevice.Alarm
    ALARM_13: UniversalDevice.Alarm
    ALARM_14: UniversalDevice.Alarm
    ALARM_15: UniversalDevice.Alarm
    ALARM_16: UniversalDevice.Alarm
    ALARM_17: UniversalDevice.Alarm
    ALARM_18: UniversalDevice.Alarm
    ALARM_19: UniversalDevice.Alarm
    ALARM_20: UniversalDevice.Alarm
    ALARM_21: UniversalDevice.Alarm
    ALARM_22: UniversalDevice.Alarm
    ALARM_23: UniversalDevice.Alarm
    ALARM_24: UniversalDevice.Alarm
    ALARM_25: UniversalDevice.Alarm
    ALARM_26: UniversalDevice.Alarm
    ALARM_27: UniversalDevice.Alarm
    ALARM_28: UniversalDevice.Alarm
    ALARM_29: UniversalDevice.Alarm
    ALARM_30: UniversalDevice.Alarm
    ALARM_31: UniversalDevice.Alarm
    ALARM_32: UniversalDevice.Alarm
    class Subtype(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
        __slots__ = ()
        NO_SUBTYPE: _ClassVar[UniversalDevice.Subtype]
    NO_SUBTYPE: UniversalDevice.Subtype
    COMMON_PART_FIELD_NUMBER: _ClassVar[int]
    DEVICE_DEBUG_ENABLED_FIELD_NUMBER: _ClassVar[int]
    SETTINGS_FIELD_NUMBER: _ClassVar[int]
    STATUSES_FIELD_NUMBER: _ClassVar[int]
    ALARMS_FIELD_NUMBER: _ClassVar[int]
    SUBTYPE_FIELD_NUMBER: _ClassVar[int]
    common_part: _common_device_pb2.CommonDevicePart
    device_debug_enabled: bool
    settings: _containers.RepeatedScalarFieldContainer[UniversalDevice.Setting]
    statuses: _containers.RepeatedScalarFieldContainer[UniversalDevice.Status]
    alarms: _containers.RepeatedScalarFieldContainer[UniversalDevice.Alarm]
    subtype: UniversalDevice.Subtype
    def __init__(self, common_part: _Optional[_Union[_common_device_pb2.CommonDevicePart, _Mapping]] = ..., device_debug_enabled: bool = ..., settings: _Optional[_Iterable[_Union[UniversalDevice.Setting, str]]] = ..., statuses: _Optional[_Iterable[_Union[UniversalDevice.Status, str]]] = ..., alarms: _Optional[_Iterable[_Union[UniversalDevice.Alarm, str]]] = ..., subtype: _Optional[_Union[UniversalDevice.Subtype, str]] = ...) -> None: ...
