# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/accounting/source_type.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/accounting/source_type.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nlsystems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/accounting/source_type.proto\x12Zsystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.accounting*\x82\x01\n AccountingNotificationSourceType\x12\x33\n/ACCOUNTING_NOTIFICATION_SOURCE_TYPE_UNSPECIFIED\x10\x00\x12\x07\n\x03HUB\x10\x01\x12\x0e\n\nVIDEO_EDGE\x10\x02\x12\x10\n\x0cSUBSCRIPTION\x10\x03\x42\x61\nZsystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.accountingP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.accounting.source_type_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nZsystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.accountingP\001\272\002\000'
  _globals['_ACCOUNTINGNOTIFICATIONSOURCETYPE']._serialized_start=205
  _globals['_ACCOUNTINGNOTIFICATIONSOURCETYPE']._serialized_end=335
# @@protoc_insertion_point(module_scope)
