from v3.mobilegwsvc.service.reject_request_for_temporary_video_edge_channel_permissions import request_pb2 as _request_pb2
from v3.mobilegwsvc.service.reject_request_for_temporary_video_edge_channel_permissions import response_pb2 as _response_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
