# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/update_day_alarm_zone_event_config/endpoint.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/update_day_alarm_zone_event_config/endpoint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.v3.mobilegwsvc.service.update_day_alarm_zone_event_config import request_pb2 as v3_dot_mobilegwsvc_dot_service_dot_update__day__alarm__zone__event__config_dot_request__pb2
from custom_components.ajax.v3.mobilegwsvc.service.update_day_alarm_zone_event_config import response_pb2 as v3_dot_mobilegwsvc_dot_service_dot_update__day__alarm__zone__event__config_dot_response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nHv3/mobilegwsvc/service/update_day_alarm_zone_event_config/endpoint.proto\x12Tsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.update_day_alarm_zone_event_config\x1aGv3/mobilegwsvc/service/update_day_alarm_zone_event_config/request.proto\x1aHv3/mobilegwsvc/service/update_day_alarm_zone_event_config/response.proto2\xab\x02\n$UpdateDayAlarmZoneEventConfigService\x12\x82\x02\n\x07\x65xecute\x12z.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.update_day_alarm_zone_event_config.UpdateDayAlarmZoneEventConfigRequest\x1a{.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.update_day_alarm_zone_event_config.UpdateDayAlarmZoneEventConfigResponseB[\nTsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.update_day_alarm_zone_event_configP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.update_day_alarm_zone_event_config.endpoint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nTsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.update_day_alarm_zone_event_configP\001\272\002\000'
  _globals['_UPDATEDAYALARMZONEEVENTCONFIGSERVICE']._serialized_start=310
  _globals['_UPDATEDAYALARMZONEEVENTCONFIGSERVICE']._serialized_end=609
# @@protoc_insertion_point(module_scope)
