from v3.mobilegwsvc.service.set_video_edge_detectors_enabled_by_notification_types import request_pb2 as _request_pb2
from v3.mobilegwsvc.service.set_video_edge_detectors_enabled_by_notification_types import response_pb2 as _response_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
