# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/set_video_edge_channel_smart_backlight_trigger_settings/response.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/set_video_edge_channel_smart_backlight_trigger_settings/response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.v3.mobilegwsvc.commonmodels.response import response_pb2 as v3_dot_mobilegwsvc_dot_commonmodels_dot_response_dot_response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n]v3/mobilegwsvc/service/set_video_edge_channel_smart_backlight_trigger_settings/response.proto\x12isystems.ajax.api.ecosystem.v3.mobilegwsvc.service.set_video_edge_channel_smart_backlight_trigger_settings\x1a\x33v3/mobilegwsvc/commonmodels/response/response.proto\"\xf1\x07\n8SetVideoEdgeChannelSmartBacklightTriggerSettingsResponse\x12R\n\x07success\x18\x01 \x01(\x0b\x32?.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.SuccessH\x00\x12\xbf\x01\n\x07\x66\x61ilure\x18\x02 \x01(\x0b\x32\xab\x01.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.set_video_edge_channel_smart_backlight_trigger_settings.SetVideoEdgeChannelSmartBacklightTriggerSettingsResponse.FailureH\x00\x1a\x92\x05\n\x07\x46\x61ilure\x12T\n\x0b\x62\x61\x64_request\x18\x01 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.ErrorH\x00\x12Z\n\x11permission_denied\x18\x02 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.ErrorH\x00\x12X\n\x0fspace_not_found\x18\x03 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.ErrorH\x00\x12T\n\x0bspace_armed\x18\x04 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.ErrorH\x00\x12^\n\x15video_edge_is_offline\x18\x05 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.ErrorH\x00\x12Z\n\x11\x63hannel_not_found\x18\x06 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.ErrorH\x00\x12`\n\x17\x63ommand_not_implemented\x18\x07 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.ErrorH\x00\x42\x07\n\x05\x65rrorB\n\n\x08responseBp\nisystems.ajax.api.ecosystem.v3.mobilegwsvc.service.set_video_edge_channel_smart_backlight_trigger_settingsP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.set_video_edge_channel_smart_backlight_trigger_settings.response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nisystems.ajax.api.ecosystem.v3.mobilegwsvc.service.set_video_edge_channel_smart_backlight_trigger_settingsP\001\272\002\000'
  _globals['_SETVIDEOEDGECHANNELSMARTBACKLIGHTTRIGGERSETTINGSRESPONSE']._serialized_start=258
  _globals['_SETVIDEOEDGECHANNELSMARTBACKLIGHTTRIGGERSETTINGSRESPONSE']._serialized_end=1267
  _globals['_SETVIDEOEDGECHANNELSMARTBACKLIGHTTRIGGERSETTINGSRESPONSE_FAILURE']._serialized_start=597
  _globals['_SETVIDEOEDGECHANNELSMARTBACKLIGHTTRIGGERSETTINGSRESPONSE_FAILURE']._serialized_end=1255
# @@protoc_insertion_point(module_scope)
