# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/mobile/v2/connectivity/ping_pong_endpoints.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/mobile/v2/connectivity/ping_pong_endpoints.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.mobile.v2.connectivity import ping_pong_request_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_connectivity_dot_ping__pong__request__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAsystems/ajax/api/mobile/v2/connectivity/ping_pong_endpoints.proto\x12\'systems.ajax.api.mobile.v2.connectivity\x1a?systems/ajax/api/mobile/v2/connectivity/ping_pong_request.proto2\x97\x01\n\x0fPingPongService\x12\x83\x01\n\x08pingPong\x12\x38.systems.ajax.api.mobile.v2.connectivity.PingPongRequest\x1a\x39.systems.ajax.api.mobile.v2.connectivity.PingPongResponse(\x01\x30\x01\x42\x05P\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.mobile.v2.connectivity.ping_pong_endpoints_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001\272\002\000'
  _globals['_PINGPONGSERVICE']._serialized_start=176
  _globals['_PINGPONGSERVICE']._serialized_end=327
# @@protoc_insertion_point(module_scope)
