# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/find_services_available_for_reseller_on_target/endpoint.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/find_services_available_for_reseller_on_target/endpoint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.v3.mobilegwsvc.service.find_services_available_for_reseller_on_target import request_pb2 as v3_dot_mobilegwsvc_dot_service_dot_find__services__available__for__reseller__on__target_dot_request__pb2
from custom_components.ajax.v3.mobilegwsvc.service.find_services_available_for_reseller_on_target import response_pb2 as v3_dot_mobilegwsvc_dot_service_dot_find__services__available__for__reseller__on__target_dot_response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nTv3/mobilegwsvc/service/find_services_available_for_reseller_on_target/endpoint.proto\x12`systems.ajax.api.ecosystem.v3.mobilegwsvc.service.find_services_available_for_reseller_on_target\x1aSv3/mobilegwsvc/service/find_services_available_for_reseller_on_target/request.proto\x1aTv3/mobilegwsvc/service/find_services_available_for_reseller_on_target/response.proto2\xe6\x02\n/FindServicesAvailableForResellerOnTargetService\x12\xb2\x02\n\x07\x65xecute\x12\x91\x01.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.find_services_available_for_reseller_on_target.FindServicesAvailableForResellerOnTargetRequest\x1a\x92\x01.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.find_services_available_for_reseller_on_target.FindServicesAvailableForResellerOnTargetResponseBg\n`systems.ajax.api.ecosystem.v3.mobilegwsvc.service.find_services_available_for_reseller_on_targetP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.find_services_available_for_reseller_on_target.endpoint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n`systems.ajax.api.ecosystem.v3.mobilegwsvc.service.find_services_available_for_reseller_on_targetP\001\272\002\000'
  _globals['_FINDSERVICESAVAILABLEFORRESELLERONTARGETSERVICE']._serialized_start=358
  _globals['_FINDSERVICESAVAILABLEFORRESELLERONTARGETSERVICE']._serialized_end=716
# @@protoc_insertion_point(module_scope)
