# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/hub/log/hub-log-event-endpoints.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v1/hub/log/hub-log-event-endpoints.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.v1.hub.log import get_log_event_request_pb2 as v1_dot_hub_dot_log_dot_get__log__event__request__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(v1/hub/log/hub-log-event-endpoints.proto\x12%systems.ajax.mobilegw.grpc.v1.hub.log\x1a&v1/hub/log/get-log-event-request.proto2\x9b\x01\n\x12HubLogEventService\x12\x84\x01\n\x0bgetLogEvent\x12\x39.systems.ajax.mobilegw.grpc.v1.hub.log.GetLogEventRequest\x1a:.systems.ajax.mobilegw.grpc.v1.hub.log.GetLogEventResponseB\x08P\x01\x88\x01\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.hub.log.hub_log_event_endpoints_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001\210\001\001\272\002\000'
  _globals['_HUBLOGEVENTSERVICE']._serialized_start=124
  _globals['_HUBLOGEVENTSERVICE']._serialized_end=279
# @@protoc_insertion_point(module_scope)
