# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/mobile/v2/common/video/videoedge/archive/calendar.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/mobile/v2/common/video/videoedge/archive/calendar.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nHsystems/ajax/api/mobile/v2/common/video/videoedge/archive/calendar.proto\x12\x39systems.ajax.api.mobile.v2.common.video.videoedge.archive\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe9\x01\n\x08\x43\x61lendar\x12-\n\tstart_day\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04\x64\x61ys\x18\x02 \x01(\x0c\x12[\n\x06tz_map\x18\x03 \x03(\x0b\x32K.systems.ajax.api.mobile.v2.common.video.videoedge.archive.Calendar.TzEntry\x1a\x43\n\x07TzEntry\x12\'\n\x03\x64\x61y\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07offsets\x18\x02 \x03(\x05\x42\x05P\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.mobile.v2.common.video.videoedge.archive.calendar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001\272\002\000'
  _globals['_CALENDAR']._serialized_start=169
  _globals['_CALENDAR']._serialized_end=402
  _globals['_CALENDAR_TZENTRY']._serialized_start=335
  _globals['_CALENDAR_TZENTRY']._serialized_end=402
# @@protoc_insertion_point(module_scope)
