# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/get_rex_pairing_devices/response.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/get_rex_pairing_devices/response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.v3.mobilegwsvc.commonmodels.response import response_pb2 as v3_dot_mobilegwsvc_dot_commonmodels_dot_response_dot_response__pb2
from custom_components.ajax.v3.mobilegwsvc.commonmodels.virtualobject import selected_device_pb2 as v3_dot_mobilegwsvc_dot_commonmodels_dot_virtualobject_dot_selected__device__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=v3/mobilegwsvc/service/get_rex_pairing_devices/response.proto\x12Isystems.ajax.api.ecosystem.v3.mobilegwsvc.service.get_rex_pairing_devices\x1a\x33v3/mobilegwsvc/commonmodels/response/response.proto\x1a?v3/mobilegwsvc/commonmodels/virtualobject/selected_device.proto\"\xed\x04\n\x1cGetRexPairingDevicesResponse\x12\x82\x01\n\x07success\x18\x01 \x01(\x0b\x32o.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.get_rex_pairing_devices.GetRexPairingDevicesResponse.SuccessH\x00\x12\x82\x01\n\x07\x66\x61ilure\x18\x02 \x01(\x0b\x32o.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.get_rex_pairing_devices.GetRexPairingDevicesResponse.FailureH\x00\x1ap\n\x07Success\x12\x65\n\x07\x64\x65vices\x18\x01 \x03(\x0b\x32T.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.virtualobject.SelectedDevice\x1a\xc4\x01\n\x07\x46\x61ilure\x12T\n\x0b\x62\x61\x64_request\x18\x01 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.ErrorH\x00\x12Z\n\x11permission_denied\x18\x02 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.ErrorH\x00\x42\x07\n\x05\x65rrorB\n\n\x08responseBP\nIsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.get_rex_pairing_devicesP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.get_rex_pairing_devices.response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nIsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.get_rex_pairing_devicesP\001\272\002\000'
  _globals['_GETREXPAIRINGDEVICESRESPONSE']._serialized_start=259
  _globals['_GETREXPAIRINGDEVICESRESPONSE']._serialized_end=880
  _globals['_GETREXPAIRINGDEVICESRESPONSE_SUCCESS']._serialized_start=557
  _globals['_GETREXPAIRINGDEVICESRESPONSE_SUCCESS']._serialized_end=669
  _globals['_GETREXPAIRINGDEVICESRESPONSE_FAILURE']._serialized_start=672
  _globals['_GETREXPAIRINGDEVICESRESPONSE_FAILURE']._serialized_end=868
# @@protoc_insertion_point(module_scope)
