# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/mobile/v2/notificationlog/stream_all_unread_counters.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/mobile/v2/notificationlog/stream_all_unread_counters.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.mobile.v2.common.response import response_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_common_dot_response_dot_response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nKsystems/ajax/api/mobile/v2/notificationlog/stream_all_unread_counters.proto\x12\'systems.ajax.api.mobile.v2.notification\x1a\x39systems/ajax/api/mobile/v2/common/response/response.proto\"\xc4\x01\n\x1eStreamAllUnreadCountersRequest\x12x\n\x14\x63ounters_origin_type\x18\x01 \x01(\x0e\x32Z.systems.ajax.api.mobile.v2.notification.StreamAllUnreadCountersRequest.CountersOriginType\"(\n\x12\x43ountersOriginType\x12\t\n\x05SPACE\x10\x00\x12\x07\n\x03HUB\x10\x01\"\x80\x05\n\x1fStreamAllUnreadCountersResponse\x12\x63\n\x07success\x18\x01 \x01(\x0b\x32P.systems.ajax.api.mobile.v2.notification.StreamAllUnreadCountersResponse.SuccessH\x00\x12\x63\n\x07\x66\x61ilure\x18\x02 \x01(\x0b\x32P.systems.ajax.api.mobile.v2.notification.StreamAllUnreadCountersResponse.FailureH\x00\x1a\xc6\x01\n\x07Success\x12|\n\x0forigin_counters\x18\x01 \x03(\x0b\x32\x63.systems.ajax.api.mobile.v2.notification.StreamAllUnreadCountersResponse.Success.OriginTotalCounter\x1a=\n\x12OriginTotalCounter\x12\x10\n\x08originId\x18\x01 \x01(\t\x12\x15\n\rtotal_counter\x18\x02 \x01(\x05\x1a\xbd\x01\n\x07\x46\x61ilure\x12T\n\x10illegal_argument\x18\x01 \x01(\x0b\x32\x38.systems.ajax.api.mobile.v2.common.response.DefaultErrorH\x00\x12R\n\x0einternal_error\x18\x02 \x01(\x0b\x32\x38.systems.ajax.api.mobile.v2.common.response.DefaultErrorH\x00\x42\x08\n\x06\x65rrorsB\n\n\x08responseB4\n*systems.ajax.api.mobile.v2.notificationlogP\x01\x88\x01\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.mobile.v2.notificationlog.stream_all_unread_counters_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n*systems.ajax.api.mobile.v2.notificationlogP\001\210\001\001\272\002\000'
  _globals['_STREAMALLUNREADCOUNTERSREQUEST']._serialized_start=180
  _globals['_STREAMALLUNREADCOUNTERSREQUEST']._serialized_end=376
  _globals['_STREAMALLUNREADCOUNTERSREQUEST_COUNTERSORIGINTYPE']._serialized_start=336
  _globals['_STREAMALLUNREADCOUNTERSREQUEST_COUNTERSORIGINTYPE']._serialized_end=376
  _globals['_STREAMALLUNREADCOUNTERSRESPONSE']._serialized_start=379
  _globals['_STREAMALLUNREADCOUNTERSRESPONSE']._serialized_end=1019
  _globals['_STREAMALLUNREADCOUNTERSRESPONSE_SUCCESS']._serialized_start=617
  _globals['_STREAMALLUNREADCOUNTERSRESPONSE_SUCCESS']._serialized_end=815
  _globals['_STREAMALLUNREADCOUNTERSRESPONSE_SUCCESS_ORIGINTOTALCOUNTER']._serialized_start=754
  _globals['_STREAMALLUNREADCOUNTERSRESPONSE_SUCCESS_ORIGINTOTALCOUNTER']._serialized_end=815
  _globals['_STREAMALLUNREADCOUNTERSRESPONSE_FAILURE']._serialized_start=818
  _globals['_STREAMALLUNREADCOUNTERSRESPONSE_FAILURE']._serialized_end=1007
# @@protoc_insertion_point(module_scope)
