# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/commonmodels/space/lock/alarm_spam_notification.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/commonmodels/space/lock/alarm_spam_notification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.v3.mobilegwsvc.commonmodels.hub.device import hub_device_view_source_pb2 as v3_dot_mobilegwsvc_dot_commonmodels_dot_hub_dot_device_dot_hub__device__view__source__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDv3/mobilegwsvc/commonmodels/space/lock/alarm_spam_notification.proto\x12\x41systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.space.lock\x1a\x43v3/mobilegwsvc/commonmodels/hub/device/hub_device_view_source.proto\"|\n\x15\x41larmSpamNotification\x12\x63\n\x0cspam_objects\x18\x01 \x03(\x0b\x32M.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.space.lock.SpamObject\"\x89\x01\n\nSpamObject\x12l\n\nhub_device\x18\x01 \x01(\x0b\x32V.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.hub.device.HubDeviceViewSourceH\x00\x42\r\n\x0bspam_objectBH\nAsystems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.space.lockP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.commonmodels.space.lock.alarm_spam_notification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nAsystems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.space.lockP\001\272\002\000'
  _globals['_ALARMSPAMNOTIFICATION']._serialized_start=208
  _globals['_ALARMSPAMNOTIFICATION']._serialized_end=332
  _globals['_SPAMOBJECT']._serialized_start=335
  _globals['_SPAMOBJECT']._serialized_end=472
# @@protoc_insertion_point(module_scope)
