# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/event/space/qualifier.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/event/space/qualifier.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.event.space import tag_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_communicationsvc_dot_mobile_dot_commonmodels_dot_event_dot_space_dot_tag__pb2
from custom_components.ajax.systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.event import transition_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_communicationsvc_dot_mobile_dot_commonmodels_dot_event_dot_transition__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n^systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/event/space/qualifier.proto\x12Nsystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.event.space\x1aXsystems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/event/space/tag.proto\x1aYsystems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/event/transition.proto\"\xf0\x01\n\x13SpaceEventQualifier\x12j\n\x03tag\x18\x01 \x01(\x0b\x32].systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.event.space.SpaceEventTag\x12m\n\ntransition\x18\x02 \x01(\x0b\x32Y.systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.event.EventTransitionBX\nNsystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.event.spaceP\x01\x88\x01\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.event.space.qualifier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nNsystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.event.spaceP\001\210\001\001\272\002\000'
  _globals['_SPACEEVENTQUALIFIER']._serialized_start=360
  _globals['_SPACEEVENTQUALIFIER']._serialized_end=600
# @@protoc_insertion_point(module_scope)
