# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/device_command_mute_all_fire_detectors_except_triggered/endpoint.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/device_command_mute_all_fire_detectors_except_triggered/endpoint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.v3.mobilegwsvc.service.device_command_mute_all_fire_detectors_except_triggered import request_pb2 as v3_dot_mobilegwsvc_dot_service_dot_device__command__mute__all__fire__detectors__except__triggered_dot_request__pb2
from custom_components.ajax.v3.mobilegwsvc.service.device_command_mute_all_fire_detectors_except_triggered import response_pb2 as v3_dot_mobilegwsvc_dot_service_dot_device__command__mute__all__fire__detectors__except__triggered_dot_response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n]v3/mobilegwsvc/service/device_command_mute_all_fire_detectors_except_triggered/endpoint.proto\x12isystems.ajax.api.ecosystem.v3.mobilegwsvc.service.device_command_mute_all_fire_detectors_except_triggered\x1a\\v3/mobilegwsvc/service/device_command_mute_all_fire_detectors_except_triggered/request.proto\x1a]v3/mobilegwsvc/service/device_command_mute_all_fire_detectors_except_triggered/response.proto2\x90\x03\n7DeviceCommandMuteAllFireDetectorsExceptTriggeredService\x12\xd4\x02\n\x07\x65xecute\x12\xa2\x01.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.device_command_mute_all_fire_detectors_except_triggered.DeviceCommandMuteAllFireDetectorsExceptTriggeredRequest\x1a\xa3\x01.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.device_command_mute_all_fire_detectors_except_triggered.DeviceCommandMuteAllFireDetectorsExceptTriggeredResponseB\x05P\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.device_command_mute_all_fire_detectors_except_triggered.endpoint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001\272\002\000'
  _globals['_DEVICECOMMANDMUTEALLFIREDETECTORSEXCEPTTRIGGEREDSERVICE']._serialized_start=394
  _globals['_DEVICECOMMANDMUTEALLFIREDETECTORSEXCEPTTRIGGEREDSERVICE']._serialized_end=794
# @@protoc_insertion_point(module_scope)
