from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class VideoNotificationObjectDetectionDuration(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    VIDEO_NOTIFICATION_OBJECT_DETECTION_DURATION_UNSPECIFIED: _ClassVar[VideoNotificationObjectDetectionDuration]
    VIDEO_NOTIFICATION_OBJECT_DETECTION_DURATION_INSTANT: _ClassVar[VideoNotificationObjectDetectionDuration]
    VIDEO_NOTIFICATION_OBJECT_DETECTION_DURATION_TWO_SECONDS: _ClassVar[VideoNotificationObjectDetectionDuration]
    VIDEO_NOTIFICATION_OBJECT_DETECTION_DURATION_THREE_SECONDS: _ClassVar[VideoNotificationObjectDetectionDuration]
    VIDEO_NOTIFICATION_OBJECT_DETECTION_DURATION_FOUR_SECONDS: _ClassVar[VideoNotificationObjectDetectionDuration]
    VIDEO_NOTIFICATION_OBJECT_DETECTION_DURATION_FIVE_SECONDS: _ClassVar[VideoNotificationObjectDetectionDuration]
VIDEO_NOTIFICATION_OBJECT_DETECTION_DURATION_UNSPECIFIED: VideoNotificationObjectDetectionDuration
VIDEO_NOTIFICATION_OBJECT_DETECTION_DURATION_INSTANT: VideoNotificationObjectDetectionDuration
VIDEO_NOTIFICATION_OBJECT_DETECTION_DURATION_TWO_SECONDS: VideoNotificationObjectDetectionDuration
VIDEO_NOTIFICATION_OBJECT_DETECTION_DURATION_THREE_SECONDS: VideoNotificationObjectDetectionDuration
VIDEO_NOTIFICATION_OBJECT_DETECTION_DURATION_FOUR_SECONDS: VideoNotificationObjectDetectionDuration
VIDEO_NOTIFICATION_OBJECT_DETECTION_DURATION_FIVE_SECONDS: VideoNotificationObjectDetectionDuration
