# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/stream_scan_fibra_devices_updates/request.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/stream_scan_fibra_devices_updates/request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nFv3/mobilegwsvc/service/stream_scan_fibra_devices_updates/request.proto\x12Ssystems.ajax.api.ecosystem.v3.mobilegwsvc.service.stream_scan_fibra_devices_updates\"6\n$StreamScanFibraDevicesUpdatesRequest\x12\x0e\n\x06hub_id\x18\x01 \x01(\tBZ\nSsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.stream_scan_fibra_devices_updatesP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.stream_scan_fibra_devices_updates.request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nSsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.stream_scan_fibra_devices_updatesP\001\272\002\000'
  _globals['_STREAMSCANFIBRADEVICESUPDATESREQUEST']._serialized_start=159
  _globals['_STREAMSCANFIBRADEVICESUPDATESREQUEST']._serialized_end=213
# @@protoc_insertion_point(module_scope)
