# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/device_command_sound_off/endpoint.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/device_command_sound_off/endpoint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.v3.mobilegwsvc.service.device_command_sound_off import request_pb2 as v3_dot_mobilegwsvc_dot_service_dot_device__command__sound__off_dot_request__pb2
from custom_components.ajax.v3.mobilegwsvc.service.device_command_sound_off import response_pb2 as v3_dot_mobilegwsvc_dot_service_dot_device__command__sound__off_dot_response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>v3/mobilegwsvc/service/device_command_sound_off/endpoint.proto\x12Jsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.device_command_sound_off\x1a=v3/mobilegwsvc/service/device_command_sound_off/request.proto\x1a>v3/mobilegwsvc/service/device_command_sound_off/response.proto2\xff\x01\n\x1c\x44\x65viceCommandSoundOffService\x12\xde\x01\n\x07\x65xecute\x12h.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.device_command_sound_off.DeviceCommandSoundOffRequest\x1ai.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.device_command_sound_off.DeviceCommandSoundOffResponseB\x05P\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.device_command_sound_off.endpoint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001\272\002\000'
  _globals['_DEVICECOMMANDSOUNDOFFSERVICE']._serialized_start=270
  _globals['_DEVICECOMMANDSOUNDOFFSERVICE']._serialized_end=525
# @@protoc_insertion_point(module_scope)
