# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/device_command_sound_off/request.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/device_command_sound_off/request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels import object_type_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_object__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=v3/mobilegwsvc/service/device_command_sound_off/request.proto\x12Jsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.device_command_sound_off\x1a\x43systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/object_type.proto\"\xa6\x03\n\x1c\x44\x65viceCommandSoundOffRequest\x12\x0e\n\x06hub_id\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12R\n\x0bobject_type\x18\x03 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.ObjectType\x12\x93\x01\n\x11mute_source_alarm\x18\x04 \x03(\x0e\x32x.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.device_command_sound_off.DeviceCommandSoundOffRequest.MuteSourceAlarm\"y\n\x0fMuteSourceAlarm\x12!\n\x1dMUTE_SOURCE_ALARM_UNSPECIFIED\x10\x00\x12\x1e\n\x1aMUTE_SOURCE_ALARM_MUTE_OWN\x10\x01\x12#\n\x1fMUTE_SOURCE_ALARM_MUTE_EXTERNAL\x10\x02\x42\x05P\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.device_command_sound_off.request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001\272\002\000'
  _globals['_DEVICECOMMANDSOUNDOFFREQUEST']._serialized_start=211
  _globals['_DEVICECOMMANDSOUNDOFFREQUEST']._serialized_end=633
  _globals['_DEVICECOMMANDSOUNDOFFREQUEST_MUTESOURCEALARM']._serialized_start=512
  _globals['_DEVICECOMMANDSOUNDOFFREQUEST_MUTESOURCEALARM']._serialized_end=633
# @@protoc_insertion_point(module_scope)
