# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/commonmodels/company/company_provided_service.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/commonmodels/company/company_provided_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBv3/mobilegwsvc/commonmodels/company/company_provided_service.proto\x12>systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.company*\x96\x01\n\x16\x43ompanyProvidedService\x12(\n$COMPANY_PROVIDED_SERVICE_UNSPECIFIED\x10\x00\x12)\n%COMPANY_PROVIDED_SERVICE_INSTALLATION\x10\x01\x12\'\n#COMPANY_PROVIDED_SERVICE_MONITORING\x10\x02\x42\x45\n>systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.companyP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.commonmodels.company.company_provided_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n>systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.companyP\001\272\002\000'
  _globals['_COMPANYPROVIDEDSERVICE']._serialized_start=135
  _globals['_COMPANYPROVIDEDSERVICE']._serialized_end=285
# @@protoc_insertion_point(module_scope)
