# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/commonmodels/company/lite_space_company.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/commonmodels/company/lite_space_company.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.mobile.v2.hubobject.model.company import company_info_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_hubobject_dot_model_dot_company_dot_company__info__pb2
from custom_components.ajax.v3.mobilegwsvc.commonmodels.company import company_provided_service_pb2 as v3_dot_mobilegwsvc_dot_commonmodels_dot_company_dot_company__provided__service__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<v3/mobilegwsvc/commonmodels/company/lite_space_company.proto\x12>systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.company\x1a\x45systems/ajax/api/mobile/v2/hubobject/model/company/company_info.proto\x1a\x42v3/mobilegwsvc/commonmodels/company/company_provided_service.proto\"\xc2\x02\n\x10LiteSpaceCompany\x12U\n\x0c\x63ompany_info\x18\x01 \x01(\x0b\x32?.systems.ajax.api.mobile.v2.hubobject.model.company.CompanyInfo\x12\x17\n\x0fspace_member_id\x18\x02 \x01(\t\x12\x1b\n\x0ehub_user_index\x18\x03 \x01(\x05H\x00\x88\x01\x01\x12\x13\n\x0bsorting_key\x18\x04 \x01(\t\x12y\n\x19\x63ompany_provided_services\x18\x05 \x03(\x0e\x32V.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.company.CompanyProvidedServiceB\x11\n\x0f_hub_user_indexBE\n>systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.companyP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.commonmodels.company.lite_space_company_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n>systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.companyP\001\272\002\000'
  _globals['_LITESPACECOMPANY']._serialized_start=268
  _globals['_LITESPACECOMPANY']._serialized_end=590
# @@protoc_insertion_point(module_scope)
