# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/ask_video_edge_direct_connect_access/endpoint.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/ask_video_edge_direct_connect_access/endpoint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.v3.mobilegwsvc.service.ask_video_edge_direct_connect_access import request_pb2 as v3_dot_mobilegwsvc_dot_service_dot_ask__video__edge__direct__connect__access_dot_request__pb2
from custom_components.ajax.v3.mobilegwsvc.service.ask_video_edge_direct_connect_access import response_pb2 as v3_dot_mobilegwsvc_dot_service_dot_ask__video__edge__direct__connect__access_dot_response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nJv3/mobilegwsvc/service/ask_video_edge_direct_connect_access/endpoint.proto\x12Vsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.ask_video_edge_direct_connect_access\x1aIv3/mobilegwsvc/service/ask_video_edge_direct_connect_access/request.proto\x1aJv3/mobilegwsvc/service/ask_video_edge_direct_connect_access/response.proto2\xb5\x02\n&AskVideoEdgeDirectConnectAccessService\x12\x8a\x02\n\x07\x65xecute\x12~.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.ask_video_edge_direct_connect_access.AskVideoEdgeDirectConnectAccessRequest\x1a\x7f.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.ask_video_edge_direct_connect_access.AskVideoEdgeDirectConnectAccessResponseBb\n[systems.ajax.api.ecosystem.v3.mobilegwsvc.user.service.ask_video_edge_direct_connect_accessP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.ask_video_edge_direct_connect_access.endpoint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n[systems.ajax.api.ecosystem.v3.mobilegwsvc.user.service.ask_video_edge_direct_connect_accessP\001\272\002\000'
  _globals['_ASKVIDEOEDGEDIRECTCONNECTACCESSSERVICE']._serialized_start=318
  _globals['_ASKVIDEOEDGEDIRECTCONNECTACCESSSERVICE']._serialized_end=627
# @@protoc_insertion_point(module_scope)
