# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/delete_cross_zone/request.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/delete_cross_zone/request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6v3/mobilegwsvc/service/delete_cross_zone/request.proto\x12\x43systems.ajax.api.ecosystem.v3.mobilegwsvc.service.delete_cross_zone\"C\n\x16\x44\x65leteCrossZoneRequest\x12\x12\n\nhub_hex_id\x18\x01 \x01(\t\x12\x15\n\rcross_zone_id\x18\x02 \x01(\tBJ\nCsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.delete_cross_zoneP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.delete_cross_zone.request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nCsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.delete_cross_zoneP\001\272\002\000'
  _globals['_DELETECROSSZONEREQUEST']._serialized_start=127
  _globals['_DELETECROSSZONEREQUEST']._serialized_end=194
# @@protoc_insertion_point(module_scope)
