from google.protobuf import empty_pb2 as _empty_pb2
from v1.common import image_chunk_pb2 as _image_chunk_pb2
from v1.media import stream_media_request_pb2 as _stream_media_request_pb2
from v1.media import stream_media_response_pb2 as _stream_media_response_pb2
from v1.media import create_media_info_request_pb2 as _create_media_info_request_pb2
from v1.media import create_media_info_response_pb2 as _create_media_info_response_pb2
from v1.media import update_media_info_request_pb2 as _update_media_info_request_pb2
from v1.media import update_media_info_response_pb2 as _update_media_info_response_pb2
from v1.media import delete_media_request_pb2 as _delete_media_request_pb2
from v1.media import upload_media_response_pb2 as _upload_media_response_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
