# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from custom_components.ajax.v1.common import image_chunk_pb2 as v1_dot_common_dot_image__chunk__pb2
from custom_components.ajax.v1.media import create_media_info_request_pb2 as v1_dot_media_dot_create__media__info__request__pb2
from custom_components.ajax.v1.media import create_media_info_response_pb2 as v1_dot_media_dot_create__media__info__response__pb2
from custom_components.ajax.v1.media import delete_media_request_pb2 as v1_dot_media_dot_delete__media__request__pb2
from custom_components.ajax.v1.media import stream_media_request_pb2 as v1_dot_media_dot_stream__media__request__pb2
from custom_components.ajax.v1.media import stream_media_response_pb2 as v1_dot_media_dot_stream__media__response__pb2
from custom_components.ajax.v1.media import update_media_info_request_pb2 as v1_dot_media_dot_update__media__info__request__pb2
from custom_components.ajax.v1.media import update_media_info_response_pb2 as v1_dot_media_dot_update__media__info__response__pb2
from custom_components.ajax.v1.media import upload_media_response_pb2 as v1_dot_media_dot_upload__media__response__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in v1/media/media_endpoints_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MediaServiceStub(object):
    """media
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.streamMedia = channel.unary_stream(
                '/systems.ajax.mobilegw.grpc.v1.media.MediaService/streamMedia',
                request_serializer=v1_dot_media_dot_stream__media__request__pb2.StreamMediaRequest.SerializeToString,
                response_deserializer=v1_dot_media_dot_stream__media__response__pb2.StreamMediaResponse.FromString,
                _registered_method=True)
        self.createMediaInfo = channel.unary_unary(
                '/systems.ajax.mobilegw.grpc.v1.media.MediaService/createMediaInfo',
                request_serializer=v1_dot_media_dot_create__media__info__request__pb2.CreateMediaInfoRequest.SerializeToString,
                response_deserializer=v1_dot_media_dot_create__media__info__response__pb2.CreateMediaInfoResponse.FromString,
                _registered_method=True)
        self.updateMediaInfo = channel.unary_unary(
                '/systems.ajax.mobilegw.grpc.v1.media.MediaService/updateMediaInfo',
                request_serializer=v1_dot_media_dot_update__media__info__request__pb2.UpdateMediaInfoRequest.SerializeToString,
                response_deserializer=v1_dot_media_dot_update__media__info__response__pb2.UpdateMediaInfoResponse.FromString,
                _registered_method=True)
        self.deleteMedia = channel.unary_unary(
                '/systems.ajax.mobilegw.grpc.v1.media.MediaService/deleteMedia',
                request_serializer=v1_dot_media_dot_delete__media__request__pb2.DeleteMediaRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.uploadMedia = channel.stream_unary(
                '/systems.ajax.mobilegw.grpc.v1.media.MediaService/uploadMedia',
                request_serializer=v1_dot_common_dot_image__chunk__pb2.ImageChunk.SerializeToString,
                response_deserializer=v1_dot_media_dot_upload__media__response__pb2.UploadMediaResponse.FromString,
                _registered_method=True)


class MediaServiceServicer(object):
    """media
    """

    def streamMedia(self, request, context):
        """
        Possible error statuses and corresponding error templates

        TIMEOUT - systems.ajax.mobilegw.error.timeout
        UNAUTHENTICATED = "systems.ajax.mobilegw.error.unauthenticated"
        INTERNAL_SERVICE_ERROR = "systems.ajax.mobilegw.error.internalServiceError"
        NOT_FOUND = "systems.ajax.mobilegw.error.notFound"
        INVALID_ARGUMENT = "systems.ajax.mobilegw.constraints.*"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def createMediaInfo(self, request, context):
        """
        Possible error statuses and corresponding error templates
        INVALID_ARGUMENT = "systems.ajax.mobilegw.constraints.*"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updateMediaInfo(self, request, context):
        """
        Possible error statuses and corresponding error templates
        INVALID_ARGUMENT = "systems.ajax.mobilegw.constraints.*"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteMedia(self, request, context):
        """
        Possible error statuses and corresponding error templates
        INVALID_ARGUMENT = "systems.ajax.mobilegw.constraints.*"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def uploadMedia(self, request_iterator, context):
        """
        Possible error statuses and corresponding error templates

        TIMEOUT - systems.ajax.mobilegw.error.timeout
        INVALID_ARGUMENT = "systems.ajax.mobilegw.error.invalidArgumentError"
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MediaServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'streamMedia': grpc.unary_stream_rpc_method_handler(
                    servicer.streamMedia,
                    request_deserializer=v1_dot_media_dot_stream__media__request__pb2.StreamMediaRequest.FromString,
                    response_serializer=v1_dot_media_dot_stream__media__response__pb2.StreamMediaResponse.SerializeToString,
            ),
            'createMediaInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.createMediaInfo,
                    request_deserializer=v1_dot_media_dot_create__media__info__request__pb2.CreateMediaInfoRequest.FromString,
                    response_serializer=v1_dot_media_dot_create__media__info__response__pb2.CreateMediaInfoResponse.SerializeToString,
            ),
            'updateMediaInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.updateMediaInfo,
                    request_deserializer=v1_dot_media_dot_update__media__info__request__pb2.UpdateMediaInfoRequest.FromString,
                    response_serializer=v1_dot_media_dot_update__media__info__response__pb2.UpdateMediaInfoResponse.SerializeToString,
            ),
            'deleteMedia': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteMedia,
                    request_deserializer=v1_dot_media_dot_delete__media__request__pb2.DeleteMediaRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'uploadMedia': grpc.stream_unary_rpc_method_handler(
                    servicer.uploadMedia,
                    request_deserializer=v1_dot_common_dot_image__chunk__pb2.ImageChunk.FromString,
                    response_serializer=v1_dot_media_dot_upload__media__response__pb2.UploadMediaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systems.ajax.mobilegw.grpc.v1.media.MediaService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('systems.ajax.mobilegw.grpc.v1.media.MediaService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MediaService(object):
    """media
    """

    @staticmethod
    def streamMedia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/systems.ajax.mobilegw.grpc.v1.media.MediaService/streamMedia',
            v1_dot_media_dot_stream__media__request__pb2.StreamMediaRequest.SerializeToString,
            v1_dot_media_dot_stream__media__response__pb2.StreamMediaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def createMediaInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/systems.ajax.mobilegw.grpc.v1.media.MediaService/createMediaInfo',
            v1_dot_media_dot_create__media__info__request__pb2.CreateMediaInfoRequest.SerializeToString,
            v1_dot_media_dot_create__media__info__response__pb2.CreateMediaInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updateMediaInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/systems.ajax.mobilegw.grpc.v1.media.MediaService/updateMediaInfo',
            v1_dot_media_dot_update__media__info__request__pb2.UpdateMediaInfoRequest.SerializeToString,
            v1_dot_media_dot_update__media__info__response__pb2.UpdateMediaInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def deleteMedia(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/systems.ajax.mobilegw.grpc.v1.media.MediaService/deleteMedia',
            v1_dot_media_dot_delete__media__request__pb2.DeleteMediaRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def uploadMedia(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/systems.ajax.mobilegw.grpc.v1.media.MediaService/uploadMedia',
            v1_dot_common_dot_image__chunk__pb2.ImageChunk.SerializeToString,
            v1_dot_media_dot_upload__media__response__pb2.UploadMediaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
