# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from custom_components.ajax.systems.ajax.api.mobile.v2.hub import add_hub_by_qr_request_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_hub_dot_add__hub__by__qr__request__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.hub import remove_hub_request_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_hub_dot_remove__hub__request__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.hub import transfer_hub_settings_request_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_hub_dot_transfer__hub__settings__request__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in systems/ajax/api/mobile/v2/hub/space_hub_endpoints_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SpaceHubServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.addHubByQr = channel.unary_unary(
                '/systems.ajax.api.mobile.v2.hub.SpaceHubService/addHubByQr',
                request_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_hub_dot_add__hub__by__qr__request__pb2.AddHubByQrRequest.SerializeToString,
                response_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_hub_dot_add__hub__by__qr__request__pb2.AddHubByQrResponse.FromString,
                _registered_method=True)
        self.transferHubSettings = channel.unary_unary(
                '/systems.ajax.api.mobile.v2.hub.SpaceHubService/transferHubSettings',
                request_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_hub_dot_transfer__hub__settings__request__pb2.TransferHubSettingsRequest.SerializeToString,
                response_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_hub_dot_transfer__hub__settings__request__pb2.TransferHubSettingsResponse.FromString,
                _registered_method=True)
        self.removeHub = channel.unary_unary(
                '/systems.ajax.api.mobile.v2.hub.SpaceHubService/removeHub',
                request_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_hub_dot_remove__hub__request__pb2.RemoveHubRequest.SerializeToString,
                response_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_hub_dot_remove__hub__request__pb2.RemoveHubResponse.FromString,
                _registered_method=True)


class SpaceHubServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def addHubByQr(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def transferHubSettings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def removeHub(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpaceHubServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'addHubByQr': grpc.unary_unary_rpc_method_handler(
                    servicer.addHubByQr,
                    request_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_hub_dot_add__hub__by__qr__request__pb2.AddHubByQrRequest.FromString,
                    response_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_hub_dot_add__hub__by__qr__request__pb2.AddHubByQrResponse.SerializeToString,
            ),
            'transferHubSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.transferHubSettings,
                    request_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_hub_dot_transfer__hub__settings__request__pb2.TransferHubSettingsRequest.FromString,
                    response_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_hub_dot_transfer__hub__settings__request__pb2.TransferHubSettingsResponse.SerializeToString,
            ),
            'removeHub': grpc.unary_unary_rpc_method_handler(
                    servicer.removeHub,
                    request_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_hub_dot_remove__hub__request__pb2.RemoveHubRequest.FromString,
                    response_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_hub_dot_remove__hub__request__pb2.RemoveHubResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systems.ajax.api.mobile.v2.hub.SpaceHubService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('systems.ajax.api.mobile.v2.hub.SpaceHubService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpaceHubService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def addHubByQr(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/systems.ajax.api.mobile.v2.hub.SpaceHubService/addHubByQr',
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_hub_dot_add__hub__by__qr__request__pb2.AddHubByQrRequest.SerializeToString,
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_hub_dot_add__hub__by__qr__request__pb2.AddHubByQrResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def transferHubSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/systems.ajax.api.mobile.v2.hub.SpaceHubService/transferHubSettings',
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_hub_dot_transfer__hub__settings__request__pb2.TransferHubSettingsRequest.SerializeToString,
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_hub_dot_transfer__hub__settings__request__pb2.TransferHubSettingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def removeHub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/systems.ajax.api.mobile.v2.hub.SpaceHubService/removeHub',
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_hub_dot_remove__hub__request__pb2.RemoveHubRequest.SerializeToString,
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_hub_dot_remove__hub__request__pb2.RemoveHubResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
