from v3.mobilegwsvc.service.find_all_space_members_with_enabled_group_permissions import request_pb2 as _request_pb2
from v3.mobilegwsvc.service.find_all_space_members_with_enabled_group_permissions import response_pb2 as _response_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
