# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/commonmodels/scheduled_acesss/scheduled_access.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/commonmodels/scheduled_acesss/scheduled_access.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels import object_type_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_object__type__pb2
from google.type import dayofweek_pb2 as google_dot_type_dot_dayofweek__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nCv3/mobilegwsvc/commonmodels/scheduled_acesss/scheduled_access.proto\x12Gsystems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.scheduled_access\x1a\x43systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/object_type.proto\x1a\x1bgoogle/type/dayofweek.proto\"\xce\x04\n\x0fScheduledAccess\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12p\n\x07targets\x18\x03 \x03(\x0b\x32_.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.scheduled_access.ScheduledAccess.Target\x12t\n\tschedules\x18\x04 \x03(\x0b\x32\x61.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.scheduled_access.ScheduledAccess.Schedule\x12\x0f\n\x07\x65nabled\x18\x05 \x01(\x08\x12\x1c\n\x14notification_enabled\x18\x06 \x01(\x08\x1ao\n\x06Target\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12R\n\x0b\x64\x65vice_type\x18\x02 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.ObjectType\x1a\x98\x01\n\x08Schedule\x12)\n\tweek_days\x18\x01 \x03(\x0e\x32\x16.google.type.DayOfWeek\x12\x12\n\nstart_hour\x18\x02 \x01(\x05\x12\x14\n\x0cstart_minute\x18\x03 \x01(\x05\x12\x10\n\x08\x65nd_hour\x18\x04 \x01(\x05\x12\x12\n\nend_minute\x18\x05 \x01(\x05\x12\x11\n\tis_active\x18\x06 \x01(\x08\x42N\nGsystems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.scheduled_accessP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.commonmodels.scheduled_acesss.scheduled_access_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nGsystems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.scheduled_accessP\001\272\002\000'
  _globals['_SCHEDULEDACCESS']._serialized_start=243
  _globals['_SCHEDULEDACCESS']._serialized_end=833
  _globals['_SCHEDULEDACCESS_TARGET']._serialized_start=567
  _globals['_SCHEDULEDACCESS_TARGET']._serialized_end=678
  _globals['_SCHEDULEDACCESS_SCHEDULE']._serialized_start=681
  _globals['_SCHEDULEDACCESS_SCHEDULE']._serialized_end=833
# @@protoc_insertion_point(module_scope)
