# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/get_video_edge_accelerometer_settings/response.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/get_video_edge_accelerometer_settings/response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.v3.mobilegwsvc.commonmodels.response import response_pb2 as v3_dot_mobilegwsvc_dot_commonmodels_dot_response_dot_response__pb2
from custom_components.ajax.v3.mobilegwsvc.commonmodels.video.videoedge.system import accelerometer_settings_pb2 as v3_dot_mobilegwsvc_dot_commonmodels_dot_video_dot_videoedge_dot_system_dot_accelerometer__settings__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nKv3/mobilegwsvc/service/get_video_edge_accelerometer_settings/response.proto\x12Wsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.get_video_edge_accelerometer_settings\x1a\x33v3/mobilegwsvc/commonmodels/response/response.proto\x1aOv3/mobilegwsvc/commonmodels/video/videoedge/system/accelerometer_settings.proto\"\x92\x07\n)GetVideoEdgeAccelerometerSettingsResponse\x12\x9e\x01\n\x07success\x18\x01 \x01(\x0b\x32\x8a\x01.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.get_video_edge_accelerometer_settings.GetVideoEdgeAccelerometerSettingsResponse.SuccessH\x00\x12\x9e\x01\n\x07\x66\x61ilure\x18\x02 \x01(\x0b\x32\x8a\x01.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.get_video_edge_accelerometer_settings.GetVideoEdgeAccelerometerSettingsResponse.FailureH\x00\x1a\x90\x01\n\x07Success\x12\x84\x01\n\x16\x61\x63\x63\x65lerometer_settings\x18\x01 \x01(\x0b\x32\x64.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.video.videoedge.system.AccelerometerSettings\x1a\x83\x03\n\x07\x46\x61ilure\x12T\n\x0b\x62\x61\x64_request\x18\x01 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.ErrorH\x00\x12Z\n\x11permission_denied\x18\x02 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.ErrorH\x00\x12X\n\x0fspace_not_found\x18\x04 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.ErrorH\x00\x12]\n\x14video_edge_not_found\x18\x05 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.ErrorH\x00\x42\x07\n\x05\x65rrorJ\x04\x08\x03\x10\x04\x42\n\n\x08responseB^\nWsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.get_video_edge_accelerometer_settingsP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.get_video_edge_accelerometer_settings.response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nWsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.get_video_edge_accelerometer_settingsP\001\272\002\000'
  _globals['_GETVIDEOEDGEACCELEROMETERSETTINGSRESPONSE']._serialized_start=303
  _globals['_GETVIDEOEDGEACCELEROMETERSETTINGSRESPONSE']._serialized_end=1217
  _globals['_GETVIDEOEDGEACCELEROMETERSETTINGSRESPONSE_SUCCESS']._serialized_start=671
  _globals['_GETVIDEOEDGEACCELEROMETERSETTINGSRESPONSE_SUCCESS']._serialized_end=815
  _globals['_GETVIDEOEDGEACCELEROMETERSETTINGSRESPONSE_FAILURE']._serialized_start=818
  _globals['_GETVIDEOEDGEACCELEROMETERSETTINGSRESPONSE_FAILURE']._serialized_end=1205
# @@protoc_insertion_point(module_scope)
