from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class HubRestoreAfterAlarmPermission(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    HUB_RESTORE_AFTER_ALARM_PERMISSION_UNSPECIFIED: _ClassVar[HubRestoreAfterAlarmPermission]
    HUB_RESTORE_AFTER_ALARM_PERMISSION_LID_OPENING: _ClassVar[HubRestoreAfterAlarmPermission]
    HUB_RESTORE_AFTER_ALARM_PERMISSION_SINGLE_INTRUSION_ALARM: _ClassVar[HubRestoreAfterAlarmPermission]
    HUB_RESTORE_AFTER_ALARM_PERMISSION_SINGLE_HOLDUP_ALARM: _ClassVar[HubRestoreAfterAlarmPermission]
    HUB_RESTORE_AFTER_ALARM_PERMISSION_CONFIRMED_INTRUSION_ALARM: _ClassVar[HubRestoreAfterAlarmPermission]
    HUB_RESTORE_AFTER_ALARM_PERMISSION_CONFIRMED_HOLDUP_ALARM: _ClassVar[HubRestoreAfterAlarmPermission]
    HUB_RESTORE_AFTER_ALARM_PERMISSION_EXTERNAL_POWER_FAILURE: _ClassVar[HubRestoreAfterAlarmPermission]
    HUB_RESTORE_AFTER_ALARM_PERMISSION_SERVER_CONNECTION_LOSS: _ClassVar[HubRestoreAfterAlarmPermission]
    HUB_RESTORE_AFTER_ALARM_PERMISSION_OTHER_MALFUNCTIONS: _ClassVar[HubRestoreAfterAlarmPermission]
HUB_RESTORE_AFTER_ALARM_PERMISSION_UNSPECIFIED: HubRestoreAfterAlarmPermission
HUB_RESTORE_AFTER_ALARM_PERMISSION_LID_OPENING: HubRestoreAfterAlarmPermission
HUB_RESTORE_AFTER_ALARM_PERMISSION_SINGLE_INTRUSION_ALARM: HubRestoreAfterAlarmPermission
HUB_RESTORE_AFTER_ALARM_PERMISSION_SINGLE_HOLDUP_ALARM: HubRestoreAfterAlarmPermission
HUB_RESTORE_AFTER_ALARM_PERMISSION_CONFIRMED_INTRUSION_ALARM: HubRestoreAfterAlarmPermission
HUB_RESTORE_AFTER_ALARM_PERMISSION_CONFIRMED_HOLDUP_ALARM: HubRestoreAfterAlarmPermission
HUB_RESTORE_AFTER_ALARM_PERMISSION_EXTERNAL_POWER_FAILURE: HubRestoreAfterAlarmPermission
HUB_RESTORE_AFTER_ALARM_PERMISSION_SERVER_CONNECTION_LOSS: HubRestoreAfterAlarmPermission
HUB_RESTORE_AFTER_ALARM_PERMISSION_OTHER_MALFUNCTIONS: HubRestoreAfterAlarmPermission
