# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/mobile/v2/common/space/device/device_constraints.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/mobile/v2/common/space/device/device_constraints.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nGsystems/ajax/api/mobile/v2/common/space/device/device_constraints.proto\x12.systems.ajax.api.mobile.v2.common.space.device\"j\n\x11\x44\x65viceConstraints\x12U\n\x0b\x63onstraints\x18\x01 \x03(\x0e\x32@.systems.ajax.api.mobile.v2.common.space.device.DeviceConstraint*\xd5\x03\n\x10\x44\x65viceConstraint\x12!\n\x1d\x44\x45VICE_CONSTRAINT_UNSPECIFIED\x10\x00\x12)\n%DEVICE_CONSTRAINT_DISABLE_INTERACTION\x10\x01\x12+\n\'DEVICE_CONSTRAINT_DISABLE_NOTIFICATIONS\x10\x02\x12.\n*DEVICE_CONSTRAINT_SHOW_DEVICE_AS_SUSPENDED\x10\x03\x12+\n\'DEVICE_CONSTRAINT_SHOW_DEVICE_AS_LOCKED\x10\x04\x12\x43\n?DEVICE_CONSTRAINT_DISABLE_HUB_CONNECTIVITY_SETTINGS_INTERACTION\x10\x05\x12Q\nMDEVICE_CONSTRAINT_DISABLE_HUB_CONNECTIVITY_SETTINGS_INTERACTION_ON_ACTIVATION\x10\x06\x12Q\nMDEVICE_CONSTRAINT_DISABLE_HUB_CONNECTIVITY_SETTINGS_INTERACTION_ON_SUSPENSION\x10\x07\x42\x35\n.systems.ajax.api.mobile.v2.common.space.deviceP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.mobile.v2.common.space.device.device_constraints_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n.systems.ajax.api.mobile.v2.common.space.deviceP\001\272\002\000'
  _globals['_DEVICECONSTRAINT']._serialized_start=232
  _globals['_DEVICECONSTRAINT']._serialized_end=701
  _globals['_DEVICECONSTRAINTS']._serialized_start=123
  _globals['_DEVICECONSTRAINTS']._serialized_end=229
# @@protoc_insertion_point(module_scope)
