# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/protobuf/hub/config_migration_state.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/protobuf/hub/config_migration_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.protobuf.hub import object_type_pb2 as systems_dot_ajax_dot_protobuf_dot_hub_dot_object__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6systems/ajax/protobuf/hub/config_migration_state.proto\x1a+systems/ajax/protobuf/hub/object_type.proto\"\x84\t\n\x14\x43onfigMigrationState\x12\x44\n\x13\x64\x61ta_transfer_state\x18\x01 \x01(\x0e\x32\'.ConfigMigrationState.DataTransferState\x12W\n\x1dmigration_frame_devices_state\x18\x02 \x01(\x0e\x32\x30.ConfigMigrationState.MigrationFrameDevicesState\x12Y\n\x1emigration_button_devices_state\x18\x03 \x01(\x0e\x32\x31.ConfigMigrationState.MigrationButtonDevicesState\x12?\n\x10migration_result\x18\x04 \x01(\x0e\x32%.ConfigMigrationState.MigrationResult\x12!\n\x0bobject_type\x18\xe8\x07 \x01(\x0e\x32\x0b.ObjectType\x12\x0b\n\x02id\x18\xe9\x07 \x01(\t\"o\n\x11\x44\x61taTransferState\x12\x1f\n\x1b\x44\x41TA_TRANSFER_UNKNOWN_STATE\x10\x00\x12\x1d\n\x19\x44\x41TA_TRANSFER_IN_PROGRESS\x10\x02\x12\x1a\n\x16\x44\x41TA_TRANSFER_FINISHED\x10\x03\"\xf0\x01\n\x1aMigrationFrameDevicesState\x12)\n%MIGRATION_FRAME_DEVICES_UNKNOWN_STATE\x10\x00\x12)\n%MIGRATION_FRAME_DEVICES_NOT_AVAILABLE\x10\x01\x12-\n)MIGRATION_FRAME_DEVICES_WAITING_FOR_START\x10\x02\x12\'\n#MIGRATION_FRAME_DEVICES_IN_PROGRESS\x10\x03\x12$\n MIGRATION_FRAME_DEVICES_FINISHED\x10\x04\"\xf6\x01\n\x1bMigrationButtonDevicesState\x12*\n&MIGRATION_BUTTON_DEVICES_UNKNOWN_STATE\x10\x00\x12*\n&MIGRATION_BUTTON_DEVICES_NOT_AVAILABLE\x10\x01\x12.\n*MIGRATION_BUTTON_DEVICES_WAITING_FOR_START\x10\x02\x12(\n$MIGRATION_BUTTON_DEVICES_IN_PROGRESS\x10\x03\x12%\n!MIGRATION_BUTTON_DEVICES_FINISHED\x10\x04\"\xa3\x01\n\x0fMigrationResult\x12 \n\x1cMIGRATION_RESULT_IN_PROGRESS\x10\x00\x12%\n!MIGRATION_RESULT_SERVER_TIMED_OUT\x10\x02\x12 \n\x1cMIGRATION_RESULT_FINISHED_OK\x10\x03\x12%\n!MIGRATION_RESULT_MIGRATION_FAILED\x10\x04\x42\'\n\x19systems.ajax.protobuf.hubP\x01\xba\x02\x07Systemsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.protobuf.hub.config_migration_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031systems.ajax.protobuf.hubP\001\272\002\007Systems'
  _globals['_CONFIGMIGRATIONSTATE']._serialized_start=104
  _globals['_CONFIGMIGRATIONSTATE']._serialized_end=1260
  _globals['_CONFIGMIGRATIONSTATE_DATATRANSFERSTATE']._serialized_start=491
  _globals['_CONFIGMIGRATIONSTATE_DATATRANSFERSTATE']._serialized_end=602
  _globals['_CONFIGMIGRATIONSTATE_MIGRATIONFRAMEDEVICESSTATE']._serialized_start=605
  _globals['_CONFIGMIGRATIONSTATE_MIGRATIONFRAMEDEVICESSTATE']._serialized_end=845
  _globals['_CONFIGMIGRATIONSTATE_MIGRATIONBUTTONDEVICESSTATE']._serialized_start=848
  _globals['_CONFIGMIGRATIONSTATE_MIGRATIONBUTTONDEVICESSTATE']._serialized_end=1094
  _globals['_CONFIGMIGRATIONSTATE_MIGRATIONRESULT']._serialized_start=1097
  _globals['_CONFIGMIGRATIONSTATE_MIGRATIONRESULT']._serialized_end=1260
# @@protoc_insertion_point(module_scope)
