# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/get_hub_object_indexes_info/request.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/get_hub_object_indexes_info/request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.v3.mobilegwsvc.commonmodels.hub.object import hub_object_type_with_index_pb2 as v3_dot_mobilegwsvc_dot_commonmodels_dot_hub_dot_object_dot_hub__object__type__with__index__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@v3/mobilegwsvc/service/get_hub_object_indexes_info/request.proto\x12Msystems.ajax.api.ecosystem.v3.mobilegwsvc.service.get_hub_object_indexes_info\x1aGv3/mobilegwsvc/commonmodels/hub/object/hub_object_type_with_index.proto\"\xc2\x01\n\x1eGetHubObjectIndexesInfoRequest\x12\x0e\n\x06hub_id\x18\x01 \x01(\t\x12}\n\x1ahub_object_type_with_index\x18\x02 \x01(\x0e\x32Y.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.hub.object.HubObjectTypeWithIndex\x12\x11\n\tobject_id\x18\x03 \x01(\tBT\nMsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.get_hub_object_indexes_infoP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.get_hub_object_indexes_info.request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nMsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.get_hub_object_indexes_infoP\001\272\002\000'
  _globals['_GETHUBOBJECTINDEXESINFOREQUEST']._serialized_start=221
  _globals['_GETHUBOBJECTINDEXESINFOREQUEST']._serialized_end=415
# @@protoc_insertion_point(module_scope)
