# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/device_command_disablement/request.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/device_command_disablement/request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels import object_type_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_object__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?v3/mobilegwsvc/service/device_command_disablement/request.proto\x12Lsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.device_command_disablement\x1a\x43systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/object_type.proto\"\xc4\x05\n\x1f\x44\x65viceCommandDisablementRequest\x12\x0e\n\x06hub_id\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12R\n\x0b\x64\x65vice_type\x18\x03 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.ObjectType\x12\xaa\x01\n\x1a\x65n54_disablement_endpoints\x18\x04 \x03(\x0e\x32\x85\x01.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.device_command_disablement.DeviceCommandDisablementRequest.En54DisablementEndpoint\"\xfc\x02\n\x17\x45n54DisablementEndpoint\x12)\n%EN54_DISABLEMENT_ENDPOINT_UNSPECIFIED\x10\x00\x12#\n\x1f\x45N54_DISABLEMENT_ENDPOINT_SMOKE\x10\x01\x12)\n%EN54_DISABLEMENT_ENDPOINT_TEMPERATURE\x10\x02\x12%\n!EN54_DISABLEMENT_ENDPOINT_SOUNDER\x10\x04\x12!\n\x1d\x45N54_DISABLEMENT_ENDPOINT_VAD\x10\x05\x12&\n\"EN54_DISABLEMENT_ENDPOINT_OUTPUT_1\x10\x06\x12&\n\"EN54_DISABLEMENT_ENDPOINT_OUTPUT_2\x10\x07\x12#\n\x1f\x45N54_DISABLEMENT_ENDPOINT_INPUT\x10\x08\x12!\n\x1d\x45N54_DISABLEMENT_ENDPOINT_MCP\x10\t\"\x04\x08\x03\x10\x03\x42S\nLsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.device_command_disablementP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.device_command_disablement.request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nLsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.device_command_disablementP\001\272\002\000'
  _globals['_DEVICECOMMANDDISABLEMENTREQUEST']._serialized_start=215
  _globals['_DEVICECOMMANDDISABLEMENTREQUEST']._serialized_end=923
  _globals['_DEVICECOMMANDDISABLEMENTREQUEST_EN54DISABLEMENTENDPOINT']._serialized_start=543
  _globals['_DEVICECOMMANDDISABLEMENTREQUEST_EN54DISABLEMENTENDPOINT']._serialized_end=923
# @@protoc_insertion_point(module_scope)
