# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/mobile/v2/service/hub/company/privacy/privacy_endpoints.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/mobile/v2/service/hub/company/privacy/privacy_endpoints.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.mobile.v2.service.hub.company.privacy import change_survelilance_cameras_company_access_pb2 as systems_dot_ajax_dot_mobile_dot_v2_dot_service_dot_hub_dot_company_dot_privacy_dot_change__survelilance__cameras__company__access__pb2
from custom_components.ajax.systems.ajax.mobile.v2.service.hub.company.privacy import change_photo_on_demand_company_access_pb2 as systems_dot_ajax_dot_mobile_dot_v2_dot_service_dot_hub_dot_company_dot_privacy_dot_change__photo__on__demand__company__access__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nJsystems/ajax/mobile/v2/service/hub/company/privacy/privacy_endpoints.proto\x12\x32systems.ajax.mobile.v2.service.hub.company.privacy\x1a\x63systems/ajax/mobile/v2/service/hub/company/privacy/change_survelilance_cameras_company_access.proto\x1a^systems/ajax/mobile/v2/service/hub/company/privacy/change_photo_on_demand_company_access.proto2\xe2\x03\n\x11HubPrivacyService\x12\xdd\x01\n setMotionCamPrivacyCompanyAccess\x12[.systems.ajax.mobile.v2.service.hub.company.privacy.ChangePhotoOnDemandCompanyAccessRequest\x1a\\.systems.ajax.mobile.v2.service.hub.company.privacy.ChangePhotoOnDemandCompanyAccessResponse\x12\xec\x01\n#setStreamingCamPrivacyCompanyAccess\x12\x61.systems.ajax.mobile.v2.service.hub.company.privacy.ChangeSurveillanceCamerasCompanyAccessRequest\x1a\x62.systems.ajax.mobile.v2.service.hub.company.privacy.ChangeSurveillanceCamerasCompanyAccessResponseB<\n2systems.ajax.mobile.v2.service.hub.company.privacyP\x01\x88\x01\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.mobile.v2.service.hub.company.privacy.privacy_endpoints_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n2systems.ajax.mobile.v2.service.hub.company.privacyP\001\210\001\001\272\002\000'
  _globals['_HUBPRIVACYSERVICE']._serialized_start=328
  _globals['_HUBPRIVACYSERVICE']._serialized_end=810
# @@protoc_insertion_point(module_scope)
