# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/activate_services/request.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/activate_services/request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.mobile.v2.common.accounting import feature_target_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_common_dot_accounting_dot_feature__target__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6v3/mobilegwsvc/service/activate_services/request.proto\x12\x43systems.ajax.api.ecosystem.v3.mobilegwsvc.service.activate_services\x1a\x41systems/ajax/api/mobile/v2/common/accounting/feature_target.proto\"\xb1\x03\n\x17\x41\x63tivateServicesRequest\x12\x19\n\x11\x66\x65\x61ture_target_id\x18\x01 \x03(\t\x12S\n\x0e\x66\x65\x61ture_target\x18\x02 \x01(\x0e\x32;.systems.ajax.api.mobile.v2.common.accounting.FeatureTarget\x12\x8b\x01\n\x13service_to_activate\x18\x03 \x03(\x0b\x32n.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.activate_services.ActivateServicesRequest.ServiceToActivate\x12\x13\n\x0breseller_id\x18\x04 \x01(\t\x12\x1e\n\x11\x61greement_version\x18\x05 \x01(\tH\x00\x88\x01\x01\x1aM\n\x11ServiceToActivate\x12\x14\n\nfeature_id\x18\x01 \x01(\tH\x00\x12\x14\n\npackage_id\x18\x02 \x01(\tH\x00\x42\x0c\n\nservice_idB\x14\n\x12_agreement_versionBJ\nCsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.activate_servicesP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.activate_services.request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nCsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.activate_servicesP\001\272\002\000'
  _globals['_ACTIVATESERVICESREQUEST']._serialized_start=195
  _globals['_ACTIVATESERVICESREQUEST']._serialized_end=628
  _globals['_ACTIVATESERVICESREQUEST_SERVICETOACTIVATE']._serialized_start=529
  _globals['_ACTIVATESERVICESREQUEST_SERVICETOACTIVATE']._serialized_end=606
# @@protoc_insertion_point(module_scope)
