# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/mobile/v2/video/videoedge/firmware/video_edge_firmware_endpoints.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/mobile/v2/video/videoedge/firmware/video_edge_firmware_endpoints.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.mobile.v2.video.videoedge.firmware import check_for_firmware_update_request_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_firmware_dot_check__for__firmware__update__request__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.video.videoedge.firmware import update_firmware_to_recommended_version_request_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_firmware_dot_update__firmware__to__recommended__version__request__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nWsystems/ajax/api/mobile/v2/video/videoedge/firmware/video_edge_firmware_endpoints.proto\x12\x33systems.ajax.api.mobile.v2.video.videoedge.firmware\x1a[systems/ajax/api/mobile/v2/video/videoedge/firmware/check_for_firmware_update_request.proto\x1ahsystems/ajax/api/mobile/v2/video/videoedge/firmware/update_firmware_to_recommended_version_request.proto2\xb6\x03\n\x18VideoEdgeFirmwareService\x12\xb9\x01\n\x0e\x63heckForUpdate\x12R.systems.ajax.api.mobile.v2.video.videoedge.firmware.CheckForFirmwareUpdateRequest\x1aS.systems.ajax.api.mobile.v2.video.videoedge.firmware.CheckForFirmwareUpdateResponse\x12\xdd\x01\n\x1aupdateToRecommendedVersion\x12^.systems.ajax.api.mobile.v2.video.videoedge.firmware.UpdateFirmwareToRecommendedVersionRequest\x1a_.systems.ajax.api.mobile.v2.video.videoedge.firmware.UpdateFirmwareToRecommendedVersionResponseB\x05P\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.mobile.v2.video.videoedge.firmware.video_edge_firmware_endpoints_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001\272\002\000'
  _globals['_VIDEOEDGEFIRMWARESERVICE']._serialized_start=344
  _globals['_VIDEOEDGEFIRMWARESERVICE']._serialized_end=782
# @@protoc_insertion_point(module_scope)
