from google.protobuf import empty_pb2 as _empty_pb2
from v1.installers import installers_search_request_pb2 as _installers_search_request_pb2
from v1.installers import installers_search_response_pb2 as _installers_search_response_pb2
from v1.installers import installers_invite_hub_user_request_pb2 as _installers_invite_hub_user_request_pb2
from v1.installers import installers_invite_company_request_pb2 as _installers_invite_company_request_pb2
from v1.installers import update_installation_company_permissions_request_pb2 as _update_installation_company_permissions_request_pb2
from v1.installers import installers_update_company_permissions_response_pb2 as _installers_update_company_permissions_response_pb2
from v1.installers import installers_delete_company_request_pb2 as _installers_delete_company_request_pb2
from v1.installers import claim_hub_permissions_request_pb2 as _claim_hub_permissions_request_pb2
from v1.installers import reject_company_permission_claim_request_pb2 as _reject_company_permission_claim_request_pb2
from v1.installers import approve_company_permission_claim_request_pb2 as _approve_company_permission_claim_request_pb2
from v1.installers import cancel_installation_company_permissions_request_pb2 as _cancel_installation_company_permissions_request_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
