# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/confirm_restore_password/request.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/confirm_restore_password/request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.v3.mobilegwsvc.commonmodels.type import user_role_pb2 as v3_dot_mobilegwsvc_dot_commonmodels_dot_type_dot_user__role__pb2
from custom_components.ajax.systems.ajax.logging.proto import formatting_options_pb2 as systems_dot_ajax_dot_logging_dot_proto_dot_formatting__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n=v3/mobilegwsvc/service/confirm_restore_password/request.proto\x12Jsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.confirm_restore_password\x1a\x30v3/mobilegwsvc/commonmodels/type/user_role.proto\x1a\x33systems/ajax/logging/proto/formatting_options.proto\"\xe6\x01\n\x1d\x43onfirmRestorePasswordRequest\x12\x1b\n\x0e\x65mail_or_phone\x18\x01 \x01(\tB\x03\xf8\x44\x01\x12X\n\tuser_role\x18\x02 \x01(\x0e\x32\x45.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.type.UserRole\x12\x13\n\x0bphone_token\x18\x03 \x01(\t\x12\x12\n\nmail_token\x18\x04 \x01(\t\x12%\n\x18new_password_sha256_hash\x18\x05 \x01(\tB\x03\xe8\x44\x01\x42V\nOsystems.ajax.api.ecosystem.v3.mobilegwsvc.user.service.confirm_restore_passwordP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.confirm_restore_password.request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nOsystems.ajax.api.ecosystem.v3.mobilegwsvc.user.service.confirm_restore_passwordP\001\272\002\000'
  _globals['_CONFIRMRESTOREPASSWORDREQUEST'].fields_by_name['email_or_phone']._loaded_options = None
  _globals['_CONFIRMRESTOREPASSWORDREQUEST'].fields_by_name['email_or_phone']._serialized_options = b'\370D\001'
  _globals['_CONFIRMRESTOREPASSWORDREQUEST'].fields_by_name['new_password_sha256_hash']._loaded_options = None
  _globals['_CONFIRMRESTOREPASSWORDREQUEST'].fields_by_name['new_password_sha256_hash']._serialized_options = b'\350D\001'
  _globals['_CONFIRMRESTOREPASSWORDREQUEST']._serialized_start=245
  _globals['_CONFIRMRESTOREPASSWORDREQUEST']._serialized_end=475
# @@protoc_insertion_point(module_scope)
