# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/resend_confirmation_codes/request.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/resend_confirmation_codes/request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.v3.mobilegwsvc.commonmodels.type import user_role_pb2 as v3_dot_mobilegwsvc_dot_commonmodels_dot_type_dot_user__role__pb2
from custom_components.ajax.v3.mobilegwsvc.commonmodels.type import phone_validation_type_pb2 as v3_dot_mobilegwsvc_dot_commonmodels_dot_type_dot_phone__validation__type__pb2
from custom_components.ajax.systems.ajax.logging.proto import formatting_options_pb2 as systems_dot_ajax_dot_logging_dot_proto_dot_formatting__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n>v3/mobilegwsvc/service/resend_confirmation_codes/request.proto\x12Ksystems.ajax.api.ecosystem.v3.mobilegwsvc.service.resend_confirmation_codes\x1a\x30v3/mobilegwsvc/commonmodels/type/user_role.proto\x1a<v3/mobilegwsvc/commonmodels/type/phone_validation_type.proto\x1a\x33systems/ajax/logging/proto/formatting_options.proto\"\x9a\x02\n\x1eResendConfirmationCodesRequest\x12X\n\tuser_role\x18\x01 \x01(\x0e\x32\x45.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.type.UserRole\x12\x12\n\x05\x65mail\x18\x02 \x01(\tB\x03\xf8\x44\x01\x12\x19\n\x0cphone_number\x18\x03 \x01(\tB\x03\xf8\x44\x01\x12o\n\x15phone_validation_type\x18\x04 \x01(\x0e\x32P.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.type.PhoneValidationTypeBW\nPsystems.ajax.api.ecosystem.v3.mobilegwsvc.user.service.resend_confirmation_codesP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.resend_confirmation_codes.request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nPsystems.ajax.api.ecosystem.v3.mobilegwsvc.user.service.resend_confirmation_codesP\001\272\002\000'
  _globals['_RESENDCONFIRMATIONCODESREQUEST'].fields_by_name['email']._loaded_options = None
  _globals['_RESENDCONFIRMATIONCODESREQUEST'].fields_by_name['email']._serialized_options = b'\370D\001'
  _globals['_RESENDCONFIRMATIONCODESREQUEST'].fields_by_name['phone_number']._loaded_options = None
  _globals['_RESENDCONFIRMATIONCODESREQUEST'].fields_by_name['phone_number']._serialized_options = b'\370D\001'
  _globals['_RESENDCONFIRMATIONCODESREQUEST']._serialized_start=309
  _globals['_RESENDCONFIRMATIONCODESREQUEST']._serialized_end=591
# @@protoc_insertion_point(module_scope)
