# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/folder.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/folder.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\\systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/folder.proto\x12Osystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification*\xb3\x01\n\x12NotificationFolder\x12\x16\n\x12\x46OLDER_UNSPECIFIED\x10\x00\x12\x10\n\x0c\x46OLDER_ALARM\x10\x01\x12\x16\n\x12\x46OLDER_MALFUNCTION\x10\x02\x12\x1a\n\x16\x46OLDER_USER_AUTOMATION\x10\x03\x12\x1a\n\x16\x46OLDER_HOME_AUTOMATION\x10\x04\x12\x11\n\rFOLDER_SYSTEM\x10\x05\x12\x10\n\x0c\x46OLDER_VIDEO\x10\x06\x42Y\nOsystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notificationP\x01\x88\x01\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.folder_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nOsystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notificationP\001\210\001\001\272\002\000'
  _globals['_NOTIFICATIONFOLDER']._serialized_start=178
  _globals['_NOTIFICATIONFOLDER']._serialized_end=357
# @@protoc_insertion_point(module_scope)
