# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/notification_channel.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/notification_channel.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\njsystems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/notification_channel.proto\x12Osystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification\"\x8e\x01\n\x14NotificationChannels\x12v\n\x08\x63hannels\x18\x01 \x03(\x0e\x32\x64.systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.NotificationChannel*T\n\x13NotificationChannel\x12 \n\x1cNO_NOTIFICATION_CHANNEL_INFO\x10\x00\x12\x08\n\x04PUSH\x10\x01\x12\x07\n\x03SMS\x10\x02\x12\x08\n\x04\x43\x41LL\x10\x03\x42Y\nOsystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notificationP\x01\x88\x01\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.notification_channel_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nOsystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notificationP\001\210\001\001\272\002\000'
  _globals['_NOTIFICATIONCHANNEL']._serialized_start=336
  _globals['_NOTIFICATIONCHANNEL']._serialized_end=420
  _globals['_NOTIFICATIONCHANNELS']._serialized_start=192
  _globals['_NOTIFICATIONCHANNELS']._serialized_end=334
# @@protoc_insertion_point(module_scope)
