# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from custom_components.ajax.v3.mobilegwsvc.service.stream_hub_wifi_module_firmware_update import request_pb2 as v3_dot_mobilegwsvc_dot_service_dot_stream__hub__wifi__module__firmware__update_dot_request__pb2
from custom_components.ajax.v3.mobilegwsvc.service.stream_hub_wifi_module_firmware_update import response_pb2 as v3_dot_mobilegwsvc_dot_service_dot_stream__hub__wifi__module__firmware__update_dot_response__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in v3/mobilegwsvc/service/stream_hub_wifi_module_firmware_update/endpoint_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamHubWifiModuleUpdateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.execute = channel.unary_stream(
                '/systems.ajax.api.ecosystem.v3.mobilegwsvc.service.stream_hub_wifi_module_firmware_update.StreamHubWifiModuleUpdateService/execute',
                request_serializer=v3_dot_mobilegwsvc_dot_service_dot_stream__hub__wifi__module__firmware__update_dot_request__pb2.StreamHubWifiModuleUpdateRequest.SerializeToString,
                response_deserializer=v3_dot_mobilegwsvc_dot_service_dot_stream__hub__wifi__module__firmware__update_dot_response__pb2.StreamHubWifiModuleUpdateResponse.FromString,
                _registered_method=True)


class StreamHubWifiModuleUpdateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamHubWifiModuleUpdateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'execute': grpc.unary_stream_rpc_method_handler(
                    servicer.execute,
                    request_deserializer=v3_dot_mobilegwsvc_dot_service_dot_stream__hub__wifi__module__firmware__update_dot_request__pb2.StreamHubWifiModuleUpdateRequest.FromString,
                    response_serializer=v3_dot_mobilegwsvc_dot_service_dot_stream__hub__wifi__module__firmware__update_dot_response__pb2.StreamHubWifiModuleUpdateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systems.ajax.api.ecosystem.v3.mobilegwsvc.service.stream_hub_wifi_module_firmware_update.StreamHubWifiModuleUpdateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('systems.ajax.api.ecosystem.v3.mobilegwsvc.service.stream_hub_wifi_module_firmware_update.StreamHubWifiModuleUpdateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamHubWifiModuleUpdateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/systems.ajax.api.ecosystem.v3.mobilegwsvc.service.stream_hub_wifi_module_firmware_update.StreamHubWifiModuleUpdateService/execute',
            v3_dot_mobilegwsvc_dot_service_dot_stream__hub__wifi__module__firmware__update_dot_request__pb2.StreamHubWifiModuleUpdateRequest.SerializeToString,
            v3_dot_mobilegwsvc_dot_service_dot_stream__hub__wifi__module__firmware__update_dot_response__pb2.StreamHubWifiModuleUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
