# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from custom_components.ajax.systems.ajax.api.mobile.v2.video.videoedge.diagnostics import report_problem_request_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_diagnostics_dot_report__problem__request__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.video.videoedge.diagnostics import setup_diagnostics_logging_off_request_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_diagnostics_dot_setup__diagnostics__logging__off__request__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.video.videoedge.diagnostics import setup_diagnostics_logging_on_request_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_diagnostics_dot_setup__diagnostics__logging__on__request__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in systems/ajax/api/mobile/v2/video/videoedge/diagnostics/video_edge_diagnostics_endpoints_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VideoEdgeDiagnosticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.setLoggingOn = channel.unary_unary(
                '/systems.ajax.api.mobile.v2.video.videoedge.diagnostics.VideoEdgeDiagnosticsService/setLoggingOn',
                request_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_diagnostics_dot_setup__diagnostics__logging__on__request__pb2.SetDiagnosticsLoggingOnRequest.SerializeToString,
                response_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_diagnostics_dot_setup__diagnostics__logging__on__request__pb2.SetDiagnosticsLoggingOnResponse.FromString,
                _registered_method=True)
        self.setLoggingOff = channel.unary_unary(
                '/systems.ajax.api.mobile.v2.video.videoedge.diagnostics.VideoEdgeDiagnosticsService/setLoggingOff',
                request_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_diagnostics_dot_setup__diagnostics__logging__off__request__pb2.SetDiagnosticsLoggingOffRequest.SerializeToString,
                response_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_diagnostics_dot_setup__diagnostics__logging__off__request__pb2.SetDiagnosticsLoggingOffResponse.FromString,
                _registered_method=True)
        self.reportProblem = channel.unary_unary(
                '/systems.ajax.api.mobile.v2.video.videoedge.diagnostics.VideoEdgeDiagnosticsService/reportProblem',
                request_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_diagnostics_dot_report__problem__request__pb2.ReportProblemRequest.SerializeToString,
                response_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_diagnostics_dot_report__problem__request__pb2.ReportProblemResponse.FromString,
                _registered_method=True)


class VideoEdgeDiagnosticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def setLoggingOn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def setLoggingOff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reportProblem(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VideoEdgeDiagnosticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'setLoggingOn': grpc.unary_unary_rpc_method_handler(
                    servicer.setLoggingOn,
                    request_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_diagnostics_dot_setup__diagnostics__logging__on__request__pb2.SetDiagnosticsLoggingOnRequest.FromString,
                    response_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_diagnostics_dot_setup__diagnostics__logging__on__request__pb2.SetDiagnosticsLoggingOnResponse.SerializeToString,
            ),
            'setLoggingOff': grpc.unary_unary_rpc_method_handler(
                    servicer.setLoggingOff,
                    request_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_diagnostics_dot_setup__diagnostics__logging__off__request__pb2.SetDiagnosticsLoggingOffRequest.FromString,
                    response_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_diagnostics_dot_setup__diagnostics__logging__off__request__pb2.SetDiagnosticsLoggingOffResponse.SerializeToString,
            ),
            'reportProblem': grpc.unary_unary_rpc_method_handler(
                    servicer.reportProblem,
                    request_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_diagnostics_dot_report__problem__request__pb2.ReportProblemRequest.FromString,
                    response_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_diagnostics_dot_report__problem__request__pb2.ReportProblemResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systems.ajax.api.mobile.v2.video.videoedge.diagnostics.VideoEdgeDiagnosticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('systems.ajax.api.mobile.v2.video.videoedge.diagnostics.VideoEdgeDiagnosticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VideoEdgeDiagnosticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def setLoggingOn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/systems.ajax.api.mobile.v2.video.videoedge.diagnostics.VideoEdgeDiagnosticsService/setLoggingOn',
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_diagnostics_dot_setup__diagnostics__logging__on__request__pb2.SetDiagnosticsLoggingOnRequest.SerializeToString,
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_diagnostics_dot_setup__diagnostics__logging__on__request__pb2.SetDiagnosticsLoggingOnResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def setLoggingOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/systems.ajax.api.mobile.v2.video.videoedge.diagnostics.VideoEdgeDiagnosticsService/setLoggingOff',
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_diagnostics_dot_setup__diagnostics__logging__off__request__pb2.SetDiagnosticsLoggingOffRequest.SerializeToString,
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_diagnostics_dot_setup__diagnostics__logging__off__request__pb2.SetDiagnosticsLoggingOffResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def reportProblem(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/systems.ajax.api.mobile.v2.video.videoedge.diagnostics.VideoEdgeDiagnosticsService/reportProblem',
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_diagnostics_dot_report__problem__request__pb2.ReportProblemRequest.SerializeToString,
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_diagnostics_dot_report__problem__request__pb2.ReportProblemResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
