# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/mobile/v2/common/space/space_locator.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/mobile/v2/common/space/space_locator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.logging.proto import log_marker_pb2 as systems_dot_ajax_dot_logging_dot_proto_dot_log__marker__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;systems/ajax/api/mobile/v2/common/space/space_locator.proto\x12\'systems.ajax.api.mobile.v2.common.space\x1a+systems/ajax/logging/proto/log_marker.proto\"M\n\x0cSpaceLocator\x12\x17\n\x08space_id\x18\x01 \x01(\tB\x03\xf0\x44\x02H\x00\x12\x15\n\x06hub_id\x18\x02 \x01(\tB\x03\xf0\x44\x05H\x00:\x02\x18\x01\x42\t\n\x07locatorB\x05P\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.mobile.v2.common.space.space_locator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001\272\002\000'
  _globals['_SPACELOCATOR'].fields_by_name['space_id']._loaded_options = None
  _globals['_SPACELOCATOR'].fields_by_name['space_id']._serialized_options = b'\360D\002'
  _globals['_SPACELOCATOR'].fields_by_name['hub_id']._loaded_options = None
  _globals['_SPACELOCATOR'].fields_by_name['hub_id']._serialized_options = b'\360D\005'
  _globals['_SPACELOCATOR']._loaded_options = None
  _globals['_SPACELOCATOR']._serialized_options = b'\030\001'
  _globals['_SPACELOCATOR']._serialized_start=149
  _globals['_SPACELOCATOR']._serialized_end=226
# @@protoc_insertion_point(module_scope)
