# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/mobile/v2/common/video/videoedge/channel/spacesettings/channel_space_settings.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/mobile/v2/common/video/videoedge/channel/spacesettings/channel_space_settings.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.ecosystem.v2.commonmodels.device.common import common_arming_part_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_commonmodels_dot_device_dot_common_dot_common__arming__part__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.common.space.device import device_arming_mode_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_common_dot_space_dot_device_dot_device__arming__mode__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\ndsystems/ajax/api/mobile/v2/common/video/videoedge/channel/spacesettings/channel_space_settings.proto\x12Gsystems.ajax.api.mobile.v2.common.video.videoedge.channel.spacesettings\x1aQsystems/ajax/api/ecosystem/v2/commonmodels/device/common/common_arming_part.proto\x1aGsystems/ajax/api/mobile/v2/common/space/device/device_arming_mode.proto\"\xcf\x02\n\x14\x43hannelSpaceSettings\x12\x14\n\x07room_id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x15\n\x08group_id\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x19\n\x11\x61rm_in_night_mode\x18\x03 \x01(\x08\x12\\\n\x12\x64\x65vice_arming_mode\x18\x04 \x01(\x0b\x32@.systems.ajax.api.mobile.v2.common.space.device.DeviceArmingMode\x12x\n\x13\x61rming_capabilities\x18\x05 \x03(\x0e\x32[.systems.ajax.api.ecosystem.v2.commonmodels.device.common.CommonArmingPart.ArmingCapabilityB\n\n\x08_room_idB\x0b\n\t_group_idB\x05P\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.mobile.v2.common.video.videoedge.channel.spacesettings.channel_space_settings_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001\272\002\000'
  _globals['_CHANNELSPACESETTINGS']._serialized_start=334
  _globals['_CHANNELSPACESETTINGS']._serialized_end=669
# @@protoc_insertion_point(module_scope)
