# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/photo/take_photo_part.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/photo/take_photo_part.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.meta import meta_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_meta_dot_meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n[systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/photo/take_photo_part.proto\x12\x45systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.photo\x1a\x41systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto\"\x83\x08\n\rTakePhotoPart\x12\x82\x01\n\x13take_photo_triggers\x18\x01 \x03(\x0b\x32\x65.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.photo.TakePhotoPart.TakePhotoTrigger\x12v\n\x0c\x63\x61pabilities\x18\xe8\x07 \x03(\x0e\x32_.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.photo.TakePhotoPart.Capability\x1a\xb5\x01\n\x15TakePhotoPartSettings\x12\x9b\x01\n\x13take_photo_triggers\x18\x01 \x03(\x0b\x32\x65.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.photo.TakePhotoPart.TakePhotoTriggerB\x17\xca\xe4\x30\x13take_photo_triggers\x1a\xfe\x01\n\x10TakePhotoTrigger\x12v\n\x0ctrigger_type\x18\x01 \x01(\x0e\x32`.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.photo.TakePhotoPart.TriggerType\x12r\n\nis_enabled\x18\x02 \x01(\x0e\x32^.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.photo.TakePhotoPart.IsEnabled\"\x93\x01\n\x0bTriggerType\x12\x1c\n\x18TRIGGER_TYPE_UNSPECIFIED\x10\x00\x12$\n TRIGGER_TYPE_IF_MASKING_DETECTED\x10\x01\x12\x1e\n\x1aTRIGGER_TYPE_IF_LID_OPENED\x10\x02\x12 \n\x1cTRIGGER_TYPE_IF_DEVICE_MOVED\x10\x03\"X\n\tIsEnabled\x12\x1a\n\x16IS_ENABLED_UNSPECIFIED\x10\x00\x12\x17\n\x13IS_ENABLED_DISABLED\x10\x01\x12\x16\n\x12IS_ENABLED_ENABLED\x10\x02\"L\n\nCapability\x12\x1a\n\x16\x43\x41PABILITY_UNSPECIFIED\x10\x00\x12\"\n\x1e\x43\x41PABILITY_TAKE_PHOTO_TRIGGERS\x10\x01\x42\x46\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.photo.take_photo_part_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\001\272\002\000'
  _globals['_TAKEPHOTOPART_TAKEPHOTOPARTSETTINGS'].fields_by_name['take_photo_triggers']._loaded_options = None
  _globals['_TAKEPHOTOPART_TAKEPHOTOPARTSETTINGS'].fields_by_name['take_photo_triggers']._serialized_options = b'\312\3440\023take_photo_triggers'
  _globals['_TAKEPHOTOPART']._serialized_start=234
  _globals['_TAKEPHOTOPART']._serialized_end=1261
  _globals['_TAKEPHOTOPART_TAKEPHOTOPARTSETTINGS']._serialized_start=505
  _globals['_TAKEPHOTOPART_TAKEPHOTOPARTSETTINGS']._serialized_end=686
  _globals['_TAKEPHOTOPART_TAKEPHOTOTRIGGER']._serialized_start=689
  _globals['_TAKEPHOTOPART_TAKEPHOTOTRIGGER']._serialized_end=943
  _globals['_TAKEPHOTOPART_TRIGGERTYPE']._serialized_start=946
  _globals['_TAKEPHOTOPART_TRIGGERTYPE']._serialized_end=1093
  _globals['_TAKEPHOTOPART_ISENABLED']._serialized_start=1095
  _globals['_TAKEPHOTOPART_ISENABLED']._serialized_end=1183
  _globals['_TAKEPHOTOPART_CAPABILITY']._serialized_start=1185
  _globals['_TAKEPHOTOPART_CAPABILITY']._serialized_end=1261
# @@protoc_insertion_point(module_scope)
