# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/mobile/v2/space/company/monitoring/search_monitoring_companies_request.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/mobile/v2/space/company/monitoring/search_monitoring_companies_request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.mobile.v2.common.response import response_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_common_dot_response_dot_response__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.common.space.company import space_monitoring_company_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_common_dot_space_dot_company_dot_space__monitoring__company__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n]systems/ajax/api/mobile/v2/space/company/monitoring/search_monitoring_companies_request.proto\x12\x33systems.ajax.api.mobile.v2.space.company.monitoring\x1a\x39systems/ajax/api/mobile/v2/common/response/response.proto\x1aNsystems/ajax/api/mobile/v2/common/space/company/space_monitoring_company.proto\"C\n SearchMonitoringCompaniesRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08space_id\x18\x02 \x01(\t\"\xe1\x03\n!SearchMonitoringCompaniesResponse\x12q\n\x07success\x18\x01 \x01(\x0b\x32^.systems.ajax.api.mobile.v2.space.company.monitoring.SearchMonitoringCompaniesResponse.SuccessH\x00\x12q\n\x07\x66\x61ilure\x18\x02 \x01(\x0b\x32^.systems.ajax.api.mobile.v2.space.company.monitoring.SearchMonitoringCompaniesResponse.FailureH\x00\x1a\x65\n\x07Success\x12Z\n\tcompanies\x18\x01 \x03(\x0b\x32G.systems.ajax.api.mobile.v2.common.space.company.SpaceMonitoringCompany\x1a\x63\n\x07\x46\x61ilure\x12O\n\x0b\x62\x61\x64_request\x18\x01 \x01(\x0b\x32\x38.systems.ajax.api.mobile.v2.common.response.DefaultErrorH\x00\x42\x07\n\x05\x65rrorB\n\n\x08responseB\nP\x01\xba\x02\x05Spaceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.mobile.v2.space.company.monitoring.search_monitoring_companies_request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001\272\002\005Space'
  _globals['_SEARCHMONITORINGCOMPANIESREQUEST']._serialized_start=289
  _globals['_SEARCHMONITORINGCOMPANIESREQUEST']._serialized_end=356
  _globals['_SEARCHMONITORINGCOMPANIESRESPONSE']._serialized_start=359
  _globals['_SEARCHMONITORINGCOMPANIESRESPONSE']._serialized_end=840
  _globals['_SEARCHMONITORINGCOMPANIESRESPONSE_SUCCESS']._serialized_start=626
  _globals['_SEARCHMONITORINGCOMPANIESRESPONSE_SUCCESS']._serialized_end=727
  _globals['_SEARCHMONITORINGCOMPANIESRESPONSE_FAILURE']._serialized_start=729
  _globals['_SEARCHMONITORINGCOMPANIESRESPONSE_FAILURE']._serialized_end=828
# @@protoc_insertion_point(module_scope)
