from google.protobuf import empty_pb2 as _empty_pb2
from v1.hub.privacy import privacy_access_list_stream_request_pb2 as _privacy_access_list_stream_request_pb2
from v1.hub.privacy import privacy_access_list_stream_response_pb2 as _privacy_access_list_stream_response_pb2
from v1.hub.privacy import privacy_set_streaming_cam_access_request_pb2 as _privacy_set_streaming_cam_access_request_pb2
from v1.hub.privacy import privacy_set_motion_cam_access_request_pb2 as _privacy_set_motion_cam_access_request_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
