from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class VideoNotificationMonitoringState(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    VIDEO_NOTIFICATION_MONITORING_STATE_UNSPECIFIED: _ClassVar[VideoNotificationMonitoringState]
    VIDEO_NOTIFICATION_MONITORING_STATE_WHEN_ARMED: _ClassVar[VideoNotificationMonitoringState]
    VIDEO_NOTIFICATION_MONITORING_STATE_ALWAYS: _ClassVar[VideoNotificationMonitoringState]
VIDEO_NOTIFICATION_MONITORING_STATE_UNSPECIFIED: VideoNotificationMonitoringState
VIDEO_NOTIFICATION_MONITORING_STATE_WHEN_ARMED: VideoNotificationMonitoringState
VIDEO_NOTIFICATION_MONITORING_STATE_ALWAYS: VideoNotificationMonitoringState
