# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/mobile/v2/common/space/security/space_security.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/mobile/v2/common/space/security/space_security.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.mobile.v2.common.space.security.group import group_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_common_dot_space_dot_security_dot_group_dot_group__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.common.space.security import space_security_mode_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_common_dot_space_dot_security_dot_space__security__mode__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEsystems/ajax/api/mobile/v2/common/space/security/space_security.proto\x12\x30systems.ajax.api.mobile.v2.common.space.security\x1a\x42systems/ajax/api/mobile/v2/common/space/security/group/group.proto\x1aJsystems/ajax/api/mobile/v2/common/space/security/space_security_mode.proto\"\xb1\x01\n\rSpaceSecurity\x12M\n\x06groups\x18\x01 \x03(\x0b\x32=.systems.ajax.api.mobile.v2.common.space.security.group.Group\x12Q\n\x04mode\x18\x02 \x01(\x0b\x32\x43.systems.ajax.api.mobile.v2.common.space.security.SpaceSecurityModeB\x05P\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.mobile.v2.common.space.security.space_security_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001\272\002\000'
  _globals['_SPACESECURITY']._serialized_start=268
  _globals['_SPACESECURITY']._serialized_end=445
# @@protoc_insertion_point(module_scope)
