# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/device_command_set_device_transmission_power_mode/request.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/device_command_set_device_transmission_power_mode/request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels import object_type_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_object__type__pb2
from custom_components.ajax.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common import device_transmission_power_mode_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_device_dot_common_dot_device__transmission__power__mode__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nVv3/mobilegwsvc/service/device_command_set_device_transmission_power_mode/request.proto\x12\x63systems.ajax.api.ecosystem.v3.mobilegwsvc.service.device_command_set_device_transmission_power_mode\x1a\x43systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/object_type.proto\x1a\x64systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_transmission_power_mode.proto\"\x97\x02\n2DeviceCommandSetDeviceTransmissionPowerModeRequest\x12\x0e\n\x06hub_id\x18\x01 \x01(\t\x12\x11\n\tdevice_id\x18\x02 \x01(\t\x12R\n\x0b\x64\x65vice_type\x18\x03 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.ObjectType\x12j\n\x04mode\x18\x04 \x01(\x0e\x32\\.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.DeviceTransmissionPowerModeB\x05P\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.device_command_set_device_transmission_power_mode.request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001\272\002\000'
  _globals['_DEVICECOMMANDSETDEVICETRANSMISSIONPOWERMODEREQUEST']._serialized_start=363
  _globals['_DEVICECOMMANDSETDEVICETRANSMISSIONPOWERMODEREQUEST']._serialized_end=642
# @@protoc_insertion_point(module_scope)
