# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/hub/additional/data/company_permissions_claim.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/hub/additional/data/company_permissions_claim.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.hub.additional.data import permission_claim_type_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_communicationsvc_dot_mobile_dot_commonmodels_dot_notification_dot_hub_dot_additional_dot_data_dot_permission__claim__type__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x83\x01systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/hub/additional/data/company_permissions_claim.proto\x12\x63systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.hub.additional.data\x1a\x7fsystems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/hub/additional/data/permission_claim_type.proto\"\xd9\x01\n\x17\x43ompanyPermissionsClaim\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x14\n\x0c\x63ompany_mail\x18\x02 \x01(\t\x12\x93\x01\n\x10permissions_type\x18\x03 \x01(\x0b\x32y.systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.hub.additional.data.PermissionsClaimTypeBm\ncsystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.hub.additional.dataP\x01\x88\x01\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.hub.additional.data.company_permissions_claim_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\ncsystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.hub.additional.dataP\001\210\001\001\272\002\000'
  _globals['_COMPANYPERMISSIONSCLAIM']._serialized_start=367
  _globals['_COMPANYPERMISSIONSCLAIM']._serialized_end=584
# @@protoc_insertion_point(module_scope)
