# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/hub/additional/data/initiator_name.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/hub/additional/data/initiator_name.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.logging.proto import formatting_options_pb2 as systems_dot_ajax_dot_logging_dot_proto_dot_formatting__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nxsystems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/hub/additional/data/initiator_name.proto\x12\x63systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.hub.additional.data\x1a\x33systems/ajax/logging/proto/formatting_options.proto\",\n\rInitiatorName\x12\x1b\n\x0einitiator_name\x18\x01 \x01(\tB\x03\xf8\x44\x01\x42m\ncsystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.hub.additional.dataP\x01\x88\x01\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.hub.additional.data.initiator_name_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\ncsystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.hub.additional.dataP\001\210\001\001\272\002\000'
  _globals['_INITIATORNAME'].fields_by_name['initiator_name']._loaded_options = None
  _globals['_INITIATORNAME'].fields_by_name['initiator_name']._serialized_options = b'\370D\001'
  _globals['_INITIATORNAME']._serialized_start=278
  _globals['_INITIATORNAME']._serialized_end=322
# @@protoc_insertion_point(module_scope)
