# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/update_space_member_folder_preferences/request.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/update_space_member_folder_preferences/request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.mobile.v2.common.response import response_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_common_dot_response_dot_response__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.common.space.member import display_member_notification_preferences_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_common_dot_space_dot_member_dot_display__member__notification__preferences__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nKv3/mobilegwsvc/service/update_space_member_folder_preferences/request.proto\x12Xsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.update_space_member_folder_preferences\x1a\x39systems/ajax/api/mobile/v2/common/response/response.proto\x1a\\systems/ajax/api/mobile/v2/common/space/member/display_member_notification_preferences.proto\"\x87\x05\n)UpdateSpaceMemberFolderPreferencesRequest\x12\xb5\x01\n\x10preference_patch\x18\x01 \x01(\x0b\x32\x9a\x01.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.update_space_member_folder_preferences.UpdateSpaceMemberFolderPreferencesRequest.FolderPreferencesPatch\x1a\xa1\x03\n\x16\x46olderPreferencesPatch\x12\x10\n\x08space_id\x18\x01 \x01(\t\x12\x11\n\tmember_id\x18\x02 \x01(\t\x12\xd3\x01\n\x18\x66older_preferences_patch\x18\n \x03(\x0b\x32\xb0\x01.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.update_space_member_folder_preferences.UpdateSpaceMemberFolderPreferencesRequest.FolderPreferencesPatch.FolderPreferencePatch\x1a\x8b\x01\n\x15\x46olderPreferencePatch\x12\x61\n\npreference\x18\x01 \x01(\x0e\x32M.systems.ajax.api.mobile.v2.common.space.member.DisplayMemberFolderPreference\x12\x0f\n\x07\x65nabled\x18\x02 \x01(\x08\x42_\nXsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.update_space_member_folder_preferencesP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.update_space_member_folder_preferences.request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nXsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.update_space_member_folder_preferencesP\001\272\002\000'
  _globals['_UPDATESPACEMEMBERFOLDERPREFERENCESREQUEST']._serialized_start=323
  _globals['_UPDATESPACEMEMBERFOLDERPREFERENCESREQUEST']._serialized_end=970
  _globals['_UPDATESPACEMEMBERFOLDERPREFERENCESREQUEST_FOLDERPREFERENCESPATCH']._serialized_start=553
  _globals['_UPDATESPACEMEMBERFOLDERPREFERENCESREQUEST_FOLDERPREFERENCESPATCH']._serialized_end=970
  _globals['_UPDATESPACEMEMBERFOLDERPREFERENCESREQUEST_FOLDERPREFERENCESPATCH_FOLDERPREFERENCEPATCH']._serialized_start=831
  _globals['_UPDATESPACEMEMBERFOLDERPREFERENCESREQUEST_FOLDERPREFERENCESPATCH_FOLDERPREFERENCEPATCH']._serialized_end=970
# @@protoc_insertion_point(module_scope)
