from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class DeviceState(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    DEVICE_STATE_UNSPECIFIED: _ClassVar[DeviceState]
    DEVICE_STATE_PASSIVE: _ClassVar[DeviceState]
    DEVICE_STATE_ACTIVE: _ClassVar[DeviceState]
    DEVICE_STATE_DETECTION_AREA_TEST: _ClassVar[DeviceState]
    DEVICE_STATE_RADIO_CONNECTION_TEST: _ClassVar[DeviceState]
    DEVICE_STATE_WAIT_RADIO_CONNECTION_TEST_START: _ClassVar[DeviceState]
    DEVICE_STATE_WAIT_RADIO_CONNECTION_TEST_END: _ClassVar[DeviceState]
    DEVICE_STATE_WAIT_DETECTION_AREA_TEST_START: _ClassVar[DeviceState]
    DEVICE_STATE_WAIT_DETECTION_AREA_TEST_END: _ClassVar[DeviceState]
    DEVICE_STATE_WAIT_REGISTRATION: _ClassVar[DeviceState]
    DEVICE_STATE_WAIT_RADIO_CHANNEL_TEST_START: _ClassVar[DeviceState]
    DEVICE_STATE_RADIO_CHANNEL_TEST: _ClassVar[DeviceState]
    DEVICE_STATE_WAIT_RADIO_CHANNEL_TEST_END: _ClassVar[DeviceState]
    DEVICE_STATE_CALIBRATION_IN_PROGRESS: _ClassVar[DeviceState]
    DEVICE_STATE_MAXIMUM_BUS_POWER_CONSUMPTION_TEST_IN_PROGRESS: _ClassVar[DeviceState]
    DEVICE_STATE_DEVICE_IS_IN_FILE_RECEIVING_MODE_WINGS: _ClassVar[DeviceState]
    DEVICE_STATE_DEVICE_IS_INSTALLING_FIRMWARE: _ClassVar[DeviceState]
    DEVICE_STATE_SELF_TEST_IN_PROGRESS: _ClassVar[DeviceState]
    DEVICE_STATE_VORF_TEST_START_WAITING: _ClassVar[DeviceState]
    DEVICE_STATE_VORF_TEST: _ClassVar[DeviceState]
    DEVICE_STATE_VORF_TEST_END_WAITING: _ClassVar[DeviceState]
DEVICE_STATE_UNSPECIFIED: DeviceState
DEVICE_STATE_PASSIVE: DeviceState
DEVICE_STATE_ACTIVE: DeviceState
DEVICE_STATE_DETECTION_AREA_TEST: DeviceState
DEVICE_STATE_RADIO_CONNECTION_TEST: DeviceState
DEVICE_STATE_WAIT_RADIO_CONNECTION_TEST_START: DeviceState
DEVICE_STATE_WAIT_RADIO_CONNECTION_TEST_END: DeviceState
DEVICE_STATE_WAIT_DETECTION_AREA_TEST_START: DeviceState
DEVICE_STATE_WAIT_DETECTION_AREA_TEST_END: DeviceState
DEVICE_STATE_WAIT_REGISTRATION: DeviceState
DEVICE_STATE_WAIT_RADIO_CHANNEL_TEST_START: DeviceState
DEVICE_STATE_RADIO_CHANNEL_TEST: DeviceState
DEVICE_STATE_WAIT_RADIO_CHANNEL_TEST_END: DeviceState
DEVICE_STATE_CALIBRATION_IN_PROGRESS: DeviceState
DEVICE_STATE_MAXIMUM_BUS_POWER_CONSUMPTION_TEST_IN_PROGRESS: DeviceState
DEVICE_STATE_DEVICE_IS_IN_FILE_RECEIVING_MODE_WINGS: DeviceState
DEVICE_STATE_DEVICE_IS_INSTALLING_FIRMWARE: DeviceState
DEVICE_STATE_SELF_TEST_IN_PROGRESS: DeviceState
DEVICE_STATE_VORF_TEST_START_WAITING: DeviceState
DEVICE_STATE_VORF_TEST: DeviceState
DEVICE_STATE_VORF_TEST_END_WAITING: DeviceState
