# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from custom_components.ajax.systems.ajax.api.mobile.v2.space.smartlock import add_by_external_id_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_add__by__external__id__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.space.smartlock import find_all_available_to_add_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_find__all__available__to__add__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.space.smartlock import find_all_by_space_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_find__all__by__space__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.space.smartlock import get_url_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_get__url__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.space.smartlock import lock_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_lock__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.space.smartlock import remove_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_remove__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.space.smartlock import stream_updates_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_stream__updates__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.space.smartlock import unlock_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_unlock__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.space.smartlock import update_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_update__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.space.smartlock import update_permissions_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_update__permissions__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in systems/ajax/api/mobile/v2/space/smartlock/smart_lock_service_endpoints_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SmartLockServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getUrl = channel.unary_unary(
                '/systems.ajax.api.mobile.v2.space.smartlock.SmartLockService/getUrl',
                request_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_get__url__pb2.GetUrlRequest.SerializeToString,
                response_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_get__url__pb2.GetUrlResponse.FromString,
                _registered_method=True)
        self.findAllAvailableToAdd = channel.unary_unary(
                '/systems.ajax.api.mobile.v2.space.smartlock.SmartLockService/findAllAvailableToAdd',
                request_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_find__all__available__to__add__pb2.FindAllSmartLocksAvailableToAddRequest.SerializeToString,
                response_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_find__all__available__to__add__pb2.FindAllSmartLocksAvailableToAddResponse.FromString,
                _registered_method=True)
        self.addByExternalId = channel.unary_unary(
                '/systems.ajax.api.mobile.v2.space.smartlock.SmartLockService/addByExternalId',
                request_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_add__by__external__id__pb2.AddSmartLockByExternalIdRequest.SerializeToString,
                response_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_add__by__external__id__pb2.AddSmartLockByExternalIdResponse.FromString,
                _registered_method=True)
        self.findAllBySpace = channel.unary_unary(
                '/systems.ajax.api.mobile.v2.space.smartlock.SmartLockService/findAllBySpace',
                request_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_find__all__by__space__pb2.FindAllSmartLocksBySpaceRequest.SerializeToString,
                response_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_find__all__by__space__pb2.FindAllSmartLocksBySpaceResponse.FromString,
                _registered_method=True)
        self.remove = channel.unary_unary(
                '/systems.ajax.api.mobile.v2.space.smartlock.SmartLockService/remove',
                request_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_remove__pb2.RemoveSmartLockRequest.SerializeToString,
                response_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_remove__pb2.RemoveSmartLockResponse.FromString,
                _registered_method=True)
        self.lock = channel.unary_unary(
                '/systems.ajax.api.mobile.v2.space.smartlock.SmartLockService/lock',
                request_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_lock__pb2.LockSmartLockRequest.SerializeToString,
                response_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_lock__pb2.LockSmartLockResponse.FromString,
                _registered_method=True)
        self.unlock = channel.unary_unary(
                '/systems.ajax.api.mobile.v2.space.smartlock.SmartLockService/unlock',
                request_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_unlock__pb2.UnlockSmartLockRequest.SerializeToString,
                response_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_unlock__pb2.UnlockSmartLockResponse.FromString,
                _registered_method=True)
        self.update = channel.unary_unary(
                '/systems.ajax.api.mobile.v2.space.smartlock.SmartLockService/update',
                request_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_update__pb2.UpdateSmartLockRequest.SerializeToString,
                response_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_update__pb2.UpdateSmartLockResponse.FromString,
                _registered_method=True)
        self.streamUpdates = channel.unary_stream(
                '/systems.ajax.api.mobile.v2.space.smartlock.SmartLockService/streamUpdates',
                request_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_stream__updates__pb2.StreamSmartLockUpdatesRequest.SerializeToString,
                response_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_stream__updates__pb2.StreamSmartLockUpdatesResponse.FromString,
                _registered_method=True)
        self.updatePermissions = channel.unary_unary(
                '/systems.ajax.api.mobile.v2.space.smartlock.SmartLockService/updatePermissions',
                request_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_update__permissions__pb2.UpdateSmartLockPermissionsRequest.SerializeToString,
                response_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_update__permissions__pb2.UpdateSmartLockPermissionsResponse.FromString,
                _registered_method=True)


class SmartLockServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getUrl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def findAllAvailableToAdd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def addByExternalId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def findAllBySpace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def remove(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def lock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def unlock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def streamUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def updatePermissions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SmartLockServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getUrl': grpc.unary_unary_rpc_method_handler(
                    servicer.getUrl,
                    request_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_get__url__pb2.GetUrlRequest.FromString,
                    response_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_get__url__pb2.GetUrlResponse.SerializeToString,
            ),
            'findAllAvailableToAdd': grpc.unary_unary_rpc_method_handler(
                    servicer.findAllAvailableToAdd,
                    request_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_find__all__available__to__add__pb2.FindAllSmartLocksAvailableToAddRequest.FromString,
                    response_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_find__all__available__to__add__pb2.FindAllSmartLocksAvailableToAddResponse.SerializeToString,
            ),
            'addByExternalId': grpc.unary_unary_rpc_method_handler(
                    servicer.addByExternalId,
                    request_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_add__by__external__id__pb2.AddSmartLockByExternalIdRequest.FromString,
                    response_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_add__by__external__id__pb2.AddSmartLockByExternalIdResponse.SerializeToString,
            ),
            'findAllBySpace': grpc.unary_unary_rpc_method_handler(
                    servicer.findAllBySpace,
                    request_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_find__all__by__space__pb2.FindAllSmartLocksBySpaceRequest.FromString,
                    response_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_find__all__by__space__pb2.FindAllSmartLocksBySpaceResponse.SerializeToString,
            ),
            'remove': grpc.unary_unary_rpc_method_handler(
                    servicer.remove,
                    request_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_remove__pb2.RemoveSmartLockRequest.FromString,
                    response_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_remove__pb2.RemoveSmartLockResponse.SerializeToString,
            ),
            'lock': grpc.unary_unary_rpc_method_handler(
                    servicer.lock,
                    request_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_lock__pb2.LockSmartLockRequest.FromString,
                    response_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_lock__pb2.LockSmartLockResponse.SerializeToString,
            ),
            'unlock': grpc.unary_unary_rpc_method_handler(
                    servicer.unlock,
                    request_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_unlock__pb2.UnlockSmartLockRequest.FromString,
                    response_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_unlock__pb2.UnlockSmartLockResponse.SerializeToString,
            ),
            'update': grpc.unary_unary_rpc_method_handler(
                    servicer.update,
                    request_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_update__pb2.UpdateSmartLockRequest.FromString,
                    response_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_update__pb2.UpdateSmartLockResponse.SerializeToString,
            ),
            'streamUpdates': grpc.unary_stream_rpc_method_handler(
                    servicer.streamUpdates,
                    request_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_stream__updates__pb2.StreamSmartLockUpdatesRequest.FromString,
                    response_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_stream__updates__pb2.StreamSmartLockUpdatesResponse.SerializeToString,
            ),
            'updatePermissions': grpc.unary_unary_rpc_method_handler(
                    servicer.updatePermissions,
                    request_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_update__permissions__pb2.UpdateSmartLockPermissionsRequest.FromString,
                    response_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_update__permissions__pb2.UpdateSmartLockPermissionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systems.ajax.api.mobile.v2.space.smartlock.SmartLockService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('systems.ajax.api.mobile.v2.space.smartlock.SmartLockService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SmartLockService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getUrl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/systems.ajax.api.mobile.v2.space.smartlock.SmartLockService/getUrl',
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_get__url__pb2.GetUrlRequest.SerializeToString,
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_get__url__pb2.GetUrlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def findAllAvailableToAdd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/systems.ajax.api.mobile.v2.space.smartlock.SmartLockService/findAllAvailableToAdd',
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_find__all__available__to__add__pb2.FindAllSmartLocksAvailableToAddRequest.SerializeToString,
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_find__all__available__to__add__pb2.FindAllSmartLocksAvailableToAddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def addByExternalId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/systems.ajax.api.mobile.v2.space.smartlock.SmartLockService/addByExternalId',
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_add__by__external__id__pb2.AddSmartLockByExternalIdRequest.SerializeToString,
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_add__by__external__id__pb2.AddSmartLockByExternalIdResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def findAllBySpace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/systems.ajax.api.mobile.v2.space.smartlock.SmartLockService/findAllBySpace',
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_find__all__by__space__pb2.FindAllSmartLocksBySpaceRequest.SerializeToString,
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_find__all__by__space__pb2.FindAllSmartLocksBySpaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def remove(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/systems.ajax.api.mobile.v2.space.smartlock.SmartLockService/remove',
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_remove__pb2.RemoveSmartLockRequest.SerializeToString,
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_remove__pb2.RemoveSmartLockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def lock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/systems.ajax.api.mobile.v2.space.smartlock.SmartLockService/lock',
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_lock__pb2.LockSmartLockRequest.SerializeToString,
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_lock__pb2.LockSmartLockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def unlock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/systems.ajax.api.mobile.v2.space.smartlock.SmartLockService/unlock',
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_unlock__pb2.UnlockSmartLockRequest.SerializeToString,
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_unlock__pb2.UnlockSmartLockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/systems.ajax.api.mobile.v2.space.smartlock.SmartLockService/update',
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_update__pb2.UpdateSmartLockRequest.SerializeToString,
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_update__pb2.UpdateSmartLockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def streamUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/systems.ajax.api.mobile.v2.space.smartlock.SmartLockService/streamUpdates',
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_stream__updates__pb2.StreamSmartLockUpdatesRequest.SerializeToString,
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_stream__updates__pb2.StreamSmartLockUpdatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def updatePermissions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/systems.ajax.api.mobile.v2.space.smartlock.SmartLockService/updatePermissions',
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_update__permissions__pb2.UpdateSmartLockPermissionsRequest.SerializeToString,
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_smartlock_dot_update__permissions__pb2.UpdateSmartLockPermissionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
