# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/commonmodels/video/videoedge/channel/video_monitoring_state.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/commonmodels/video/videoedge/channel/video_monitoring_state.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nPv3/mobilegwsvc/commonmodels/video/videoedge/channel/video_monitoring_state.proto\x12Nsystems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.video.videoedge.channel*\x87\x01\n\x14VideoMonitoringState\x12&\n\"VIDEO_MONITORING_STATE_UNSPECIFIED\x10\x00\x12\"\n\x1eVIDEO_MONITORING_STATE_ENABLED\x10\x01\x12#\n\x1fVIDEO_MONITORING_STATE_DISABLED\x10\x02\x42U\nNsystems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.video.videoedge.channelP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.commonmodels.video.videoedge.channel.video_monitoring_state_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nNsystems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.video.videoedge.channelP\001\272\002\000'
  _globals['_VIDEOMONITORINGSTATE']._serialized_start=165
  _globals['_VIDEOMONITORINGSTATE']._serialized_end=300
# @@protoc_insertion_point(module_scope)
