# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from custom_components.ajax.systems.ajax.mobile.v2.service.hub.company.media import caputre_photo_pb2 as systems_dot_ajax_dot_mobile_dot_v2_dot_service_dot_hub_dot_company_dot_media_dot_caputre__photo__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in systems/ajax/mobile/v2/service/hub/company/media/photo_on_demand_endpoints_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PhotoOnDemandServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.capturePhoto = channel.unary_unary(
                '/systems.ajax.mobile.v2.service.hub.company.media.PhotoOnDemandService/capturePhoto',
                request_serializer=systems_dot_ajax_dot_mobile_dot_v2_dot_service_dot_hub_dot_company_dot_media_dot_caputre__photo__pb2.CapturePhotoOnDemandRequest.SerializeToString,
                response_deserializer=systems_dot_ajax_dot_mobile_dot_v2_dot_service_dot_hub_dot_company_dot_media_dot_caputre__photo__pb2.CapturePhotoOnDemandResponse.FromString,
                _registered_method=True)


class PhotoOnDemandServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def capturePhoto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PhotoOnDemandServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'capturePhoto': grpc.unary_unary_rpc_method_handler(
                    servicer.capturePhoto,
                    request_deserializer=systems_dot_ajax_dot_mobile_dot_v2_dot_service_dot_hub_dot_company_dot_media_dot_caputre__photo__pb2.CapturePhotoOnDemandRequest.FromString,
                    response_serializer=systems_dot_ajax_dot_mobile_dot_v2_dot_service_dot_hub_dot_company_dot_media_dot_caputre__photo__pb2.CapturePhotoOnDemandResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systems.ajax.mobile.v2.service.hub.company.media.PhotoOnDemandService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('systems.ajax.mobile.v2.service.hub.company.media.PhotoOnDemandService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PhotoOnDemandService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def capturePhoto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/systems.ajax.mobile.v2.service.hub.company.media.PhotoOnDemandService/capturePhoto',
            systems_dot_ajax_dot_mobile_dot_v2_dot_service_dot_hub_dot_company_dot_media_dot_caputre__photo__pb2.CapturePhotoOnDemandRequest.SerializeToString,
            systems_dot_ajax_dot_mobile_dot_v2_dot_service_dot_hub_dot_company_dot_media_dot_caputre__photo__pb2.CapturePhotoOnDemandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
