# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/get_video_notification_settings/response.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/get_video_notification_settings/response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.v3.mobilegwsvc.commonmodels.response import response_pb2 as v3_dot_mobilegwsvc_dot_commonmodels_dot_response_dot_response__pb2
from custom_components.ajax.v3.mobilegwsvc.commonmodels.video.videoedge.channel.notification import video_notification_settings_pb2 as v3_dot_mobilegwsvc_dot_commonmodels_dot_video_dot_videoedge_dot_channel_dot_notification_dot_video__notification__settings__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nEv3/mobilegwsvc/service/get_video_notification_settings/response.proto\x12Qsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.get_video_notification_settings\x1a\x33v3/mobilegwsvc/commonmodels/response/response.proto\x1a\x62v3/mobilegwsvc/commonmodels/video/videoedge/channel/notification/video_notification_settings.proto\"\xb5\x06\n$GetVideoNotificationSettingsResponse\x12\x89\x01\n\x07success\x18\x01 \x01(\x0b\x32v.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.video.videoedge.channel.notification.VideoNotificationSettingsH\x00\x12\x92\x01\n\x07\x66\x61ilure\x18\x02 \x01(\x0b\x32\x7f.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.get_video_notification_settings.GetVideoNotificationSettingsResponse.FailureH\x00\x1a\xdf\x03\n\x07\x46\x61ilure\x12T\n\x0b\x62\x61\x64_request\x18\x01 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.ErrorH\x00\x12Z\n\x11permission_denied\x18\x02 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.ErrorH\x00\x12X\n\x0fspace_not_found\x18\x04 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.ErrorH\x00\x12]\n\x14video_edge_not_found\x18\x05 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.ErrorH\x00\x12Z\n\x11\x63hannel_not_found\x18\x06 \x01(\x0b\x32=.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.ErrorH\x00\x42\x07\n\x05\x65rrorJ\x04\x08\x03\x10\x04\x42\n\n\x08responseBX\nQsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.get_video_notification_settingsP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.get_video_notification_settings.response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nQsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.get_video_notification_settingsP\001\272\002\000'
  _globals['_GETVIDEONOTIFICATIONSETTINGSRESPONSE']._serialized_start=310
  _globals['_GETVIDEONOTIFICATIONSETTINGSRESPONSE']._serialized_end=1131
  _globals['_GETVIDEONOTIFICATIONSETTINGSRESPONSE_FAILURE']._serialized_start=640
  _globals['_GETVIDEONOTIFICATIONSETTINGSRESPONSE_FAILURE']._serialized_end=1119
# @@protoc_insertion_point(module_scope)
