# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/hub/media/image_status.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/hub/media/image_status.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nlsystems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/hub/media/image_status.proto\x12Ysystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.hub.media*z\n\x0bImageStatus\x12\x1c\n\x18IMAGE_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n\x18IMAGE_STATUS_IN_PROGRESS\x10\x01\x12\x16\n\x12IMAGE_STATUS_READY\x10\x02\x12\x17\n\x13IMAGE_STATUS_FAILED\x10\x03\x42\x63\nYsystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.hub.mediaP\x01\x88\x01\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.hub.media.image_status_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nYsystems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.hub.mediaP\001\210\001\001\272\002\000'
  _globals['_IMAGESTATUS']._serialized_start=203
  _globals['_IMAGESTATUS']._serialized_end=325
# @@protoc_insertion_point(module_scope)
