# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/video/media/visibility.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/video/media/visibility.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nlsystems/ajax/api/ecosystem/v2/communicationsvc/mobile/commonmodels/notification/video/media/visibility.proto\x12[systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.video.media\"\x9e\x03\n\x14VideoMediaVisibility\x12\x90\x01\n\twhitelist\x18\x01 \x01(\x0b\x32{.systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.video.media.VideoMediaVisibility.WhitelistH\x00\x12\xa5\x01\n\x14\x61llowed_for_everyone\x18\x02 \x01(\x0b\x32\x84\x01.systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.video.media.VideoMediaVisibility.AllowedForEveryoneH\x00\x1a\'\n\tWhitelist\x12\x1a\n\x12\x61llowed_member_ids\x18\x04 \x03(\t\x1a\x14\n\x12\x41llowedForEveryoneB\x0c\n\nvisibilityBe\n[systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.video.mediaP\x01\x88\x01\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.video.media.visibility_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n[systems.ajax.api.ecosystem.v2.communicationsvc.mobile.commonmodels.notification.video.mediaP\001\210\001\001\272\002\000'
  _globals['_VIDEOMEDIAVISIBILITY']._serialized_start=206
  _globals['_VIDEOMEDIAVISIBILITY']._serialized_end=620
  _globals['_VIDEOMEDIAVISIBILITY_WHITELIST']._serialized_start=545
  _globals['_VIDEOMEDIAVISIBILITY_WHITELIST']._serialized_end=584
  _globals['_VIDEOMEDIAVISIBILITY_ALLOWEDFOREVERYONE']._serialized_start=586
  _globals['_VIDEOMEDIAVISIBILITY_ALLOWEDFOREVERYONE']._serialized_end=606
# @@protoc_insertion_point(module_scope)
