# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/mobile/v2/video/videoedge/channel/video_edge_channel_endpoints.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/mobile/v2/video/videoedge/channel/video_edge_channel_endpoints.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.mobile.v2.video.videoedge.channel import set_record_settings_request_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_channel_dot_set__record__settings__request__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.video.videoedge.channel import set_settings_request_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_video_dot_videoedge_dot_channel_dot_set__settings__request__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nUsystems/ajax/api/mobile/v2/video/videoedge/channel/video_edge_channel_endpoints.proto\x12\x32systems.ajax.api.mobile.v2.video.videoedge.channel\x1aTsystems/ajax/api/mobile/v2/video/videoedge/channel/set_record_settings_request.proto\x1aMsystems/ajax/api/mobile/v2/video/videoedge/channel/set_settings_request.proto2\x8d\x03\n\x17VideoEdgeChannelService\x12\xae\x01\n\x0bsetSettings\x12M.systems.ajax.api.mobile.v2.video.videoedge.channel.SetChannelSettingsRequest\x1aN.systems.ajax.api.mobile.v2.video.videoedge.channel.SetChannelSettingsResponse\"\x00\x12\xc0\x01\n\x11setRecordSettings\x12S.systems.ajax.api.mobile.v2.video.videoedge.channel.SetChannelRecordSettingsRequest\x1aT.systems.ajax.api.mobile.v2.video.videoedge.channel.SetChannelRecordSettingsResponse\"\x00\x42\x05P\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.mobile.v2.video.videoedge.channel.video_edge_channel_endpoints_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001\272\002\000'
  _globals['_VIDEOEDGECHANNELSERVICE']._serialized_start=307
  _globals['_VIDEOEDGECHANNELSERVICE']._serialized_end=704
# @@protoc_insertion_point(module_scope)
