from google.protobuf import empty_pb2 as _empty_pb2
from v1.user import user_stream_changes_response_pb2 as _user_stream_changes_response_pb2
from v1.user import user_stream_companies_request_pb2 as _user_stream_companies_request_pb2
from v1.user import user_stream_companies_response_pb2 as _user_stream_companies_response_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
