# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v1/user/user-stream-changes-response.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v1/user/user-stream-changes-response.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.v1.common import user_pb2 as v1_dot_common_dot_user__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*v1/user/user-stream-changes-response.proto\x12\"systems.ajax.mobilegw.grpc.v1.user\x1a\x14v1/common/user.proto\"U\n\x19UserStreamChangesResponse\x12\x38\n\x04user\x18\x01 \x01(\x0b\x32*.systems.ajax.mobilegw.grpc.v1.common.UserB)\n\"systems.ajax.mobilegw.grpc.v1.userP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v1.user.user_stream_changes_response_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\"systems.ajax.mobilegw.grpc.v1.userP\001\272\002\000'
  _globals['_USERSTREAMCHANGESRESPONSE']._serialized_start=104
  _globals['_USERSTREAMCHANGESRESPONSE']._serialized_end=189
# @@protoc_insertion_point(module_scope)
