# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from custom_components.ajax.systems.ajax.api.mobile.v2.space.image import space_image_chunk_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_image_dot_space__image__chunk__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.space.image import upload_image_response_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_image_dot_upload__image__response__pb2

GRPC_GENERATED_VERSION = '1.72.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in systems/ajax/api/mobile/v2/space/image/space_image_endpoints_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SpaceImageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.upload = channel.stream_unary(
                '/systems.ajax.api.mobile.v2.space.image.SpaceImageService/upload',
                request_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_image_dot_space__image__chunk__pb2.SpaceImageChunk.SerializeToString,
                response_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_image_dot_upload__image__response__pb2.UploadSpaceImageResponse.FromString,
                _registered_method=True)


class SpaceImageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def upload(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpaceImageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'upload': grpc.stream_unary_rpc_method_handler(
                    servicer.upload,
                    request_deserializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_image_dot_space__image__chunk__pb2.SpaceImageChunk.FromString,
                    response_serializer=systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_image_dot_upload__image__response__pb2.UploadSpaceImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'systems.ajax.api.mobile.v2.space.image.SpaceImageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('systems.ajax.api.mobile.v2.space.image.SpaceImageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SpaceImageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def upload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/systems.ajax.api.mobile.v2.space.image.SpaceImageService/upload',
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_image_dot_space__image__chunk__pb2.SpaceImageChunk.SerializeToString,
            systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_image_dot_upload__image__response__pb2.UploadSpaceImageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
