# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/mobile/v2/space/image/space-image-endpoints.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/mobile/v2/space/image/space-image-endpoints.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.mobile.v2.space.image import space_image_chunk_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_image_dot_space__image__chunk__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.space.image import upload_image_response_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_space_dot_image_dot_upload__image__response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nBsystems/ajax/api/mobile/v2/space/image/space-image-endpoints.proto\x12&systems.ajax.api.mobile.v2.space.image\x1a>systems/ajax/api/mobile/v2/space/image/space_image_chunk.proto\x1a\x42systems/ajax/api/mobile/v2/space/image/upload_image_response.proto2\x9d\x01\n\x11SpaceImageService\x12\x87\x01\n\x06upload\x12\x37.systems.ajax.api.mobile.v2.space.image.SpaceImageChunk\x1a@.systems.ajax.api.mobile.v2.space.image.UploadSpaceImageResponse\"\x00(\x01\x42\x05P\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.mobile.v2.space.image.space_image_endpoints_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001\272\002\000'
  _globals['_SPACEIMAGESERVICE']._serialized_start=243
  _globals['_SPACEIMAGESERVICE']._serialized_end=400
# @@protoc_insertion_point(module_scope)
