# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/alarm_verification.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/alarm_verification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.meta import meta_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_hubsvc_dot_commonmodels_dot_meta_dot_meta__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nXsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/alarm_verification.proto\x12?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common\x1a\x41systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/meta/meta.proto\"\x80\x04\n\x11\x41larmVerification\x12\x8d\x01\n\x0cverification\x18\x01 \x01(\x0e\x32_.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.AlarmVerification.VerificationB\x16\xca\xe4\x30\x12\x61larm_verification\x1a\xc1\x01\n\x19\x41larmVerificationSettings\x12\x92\x01\n\x0cverification\x18\x01 \x01(\x0e\x32_.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.AlarmVerification.VerificationB\x16\xca\xe4\x30\x12\x61larm_verificationH\x00\x88\x01\x01\x42\x0f\n\r_verification\"\x96\x01\n\x0cVerification\x12\x1c\n\x18VERIFICATION_UNSPECIFIED\x10\x00\x12\x34\n\x15VERIFICATION_DISABLED\x10\x01\x1a\x19\xea\xb1\x30\x15VERIFICATION_DISABLED\x12\x32\n\x14VERIFICATION_ENABLED\x10\x02\x1a\x18\xea\xb1\x30\x14VERIFICATION_ENABLEDBF\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.alarm_verification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\001\272\002\000'
  _globals['_ALARMVERIFICATION_ALARMVERIFICATIONSETTINGS'].fields_by_name['verification']._loaded_options = None
  _globals['_ALARMVERIFICATION_ALARMVERIFICATIONSETTINGS'].fields_by_name['verification']._serialized_options = b'\312\3440\022alarm_verification'
  _globals['_ALARMVERIFICATION_VERIFICATION'].values_by_name["VERIFICATION_DISABLED"]._loaded_options = None
  _globals['_ALARMVERIFICATION_VERIFICATION'].values_by_name["VERIFICATION_DISABLED"]._serialized_options = b'\352\2610\025VERIFICATION_DISABLED'
  _globals['_ALARMVERIFICATION_VERIFICATION'].values_by_name["VERIFICATION_ENABLED"]._loaded_options = None
  _globals['_ALARMVERIFICATION_VERIFICATION'].values_by_name["VERIFICATION_ENABLED"]._serialized_options = b'\352\2610\024VERIFICATION_ENABLED'
  _globals['_ALARMVERIFICATION'].fields_by_name['verification']._loaded_options = None
  _globals['_ALARMVERIFICATION'].fields_by_name['verification']._serialized_options = b'\312\3440\022alarm_verification'
  _globals['_ALARMVERIFICATION']._serialized_start=225
  _globals['_ALARMVERIFICATION']._serialized_end=737
  _globals['_ALARMVERIFICATION_ALARMVERIFICATIONSETTINGS']._serialized_start=391
  _globals['_ALARMVERIFICATION_ALARMVERIFICATIONSETTINGS']._serialized_end=584
  _globals['_ALARMVERIFICATION_VERIFICATION']._serialized_start=587
  _globals['_ALARMVERIFICATION_VERIFICATION']._serialized_end=737
# @@protoc_insertion_point(module_scope)
