# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/common_standard_compliance_part.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/common_standard_compliance_part.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.ecosystem.v2.commonmodels.device.common import security_standart_pb2 as systems_dot_ajax_dot_api_dot_ecosystem_dot_v2_dot_commonmodels_dot_device_dot_common_dot_security__standart__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nesystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/common_standard_compliance_part.proto\x12?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common\x1aPsystems/ajax/api/ecosystem/v2/commonmodels/device/common/security_standart.proto\"\x89\x05\n\x1c\x43ommonStandardCompliancePart\x12\x64\n\x10\x63urrent_standard\x18\x01 \x01(\x0e\x32J.systems.ajax.api.ecosystem.v2.commonmodels.device.common.SecurityStandard\x12\x83\x01\n\rpd_compliance\x18\x02 \x01(\x0e\x32l.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.CommonStandardCompliancePart.ComplianceInfo\x12\x83\x01\n\ren_compliance\x18\x03 \x01(\x0e\x32l.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.CommonStandardCompliancePart.ComplianceInfo\x12\x87\x01\n\x11sia_cp_compliance\x18\x04 \x01(\x0e\x32l.systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.CommonStandardCompliancePart.ComplianceInfo\"m\n\x0e\x43omplianceInfo\x12\x1f\n\x1b\x43OMPLIANCE_INFO_UNSPECIFIED\x10\x00\x12\x1d\n\x19\x43OMPLIANCE_INFO_COMPLIANT\x10\x01\x12\x1b\n\x17\x43OMPLIANCE_INFO_WARNING\x10\x02\x42\x46\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.common_standard_compliance_part_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\001\272\002\000'
  _globals['_COMMONSTANDARDCOMPLIANCEPART']._serialized_start=253
  _globals['_COMMONSTANDARDCOMPLIANCEPART']._serialized_end=902
  _globals['_COMMONSTANDARDCOMPLIANCEPART_COMPLIANCEINFO']._serialized_start=793
  _globals['_COMMONSTANDARDCOMPLIANCEPART_COMPLIANCEINFO']._serialized_end=902
# @@protoc_insertion_point(module_scope)
