# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_common_capabilities.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_common_capabilities.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n`systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/device_common_capabilities.proto\x12?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common*\xae\x03\n\x16\x44\x65viceCommonCapability\x12(\n$DEVICE_COMMON_CAPABILITY_UNSPECIFIED\x10\x00\x12$\n DEVICE_COMMON_CAPABILITY_GRADE_3\x10\x01\x12-\n)DEVICE_COMMON_CAPABILITY_POWER_MANAGEMENT\x10\t\x12-\n)DEVICE_COMMON_CAPABILITY_ATTENUATION_TEST\x10\n\x12\x34\n0DEVICE_COMMON_CAPABILITY_BRACKET_STATE_SUPPORTED\x10\x0b\x12&\n\"DEVICE_COMMON_CAPABILITY_SELF_TEST\x10\x0c\x12-\n)DEVICE_COMMON_CAPABILITY_MASK_CALIBRATION\x10\r\x12%\n!DEVICE_COMMON_CAPABILITY_SCENARIO\x10\x0e\x12\x32\n.DEVICE_COMMON_CAPABILITY_MOTION_DETECTION_AREA\x10\x0f\x42\x46\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.device_common_capabilities_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\001\272\002\000'
  _globals['_DEVICECOMMONCAPABILITY']._serialized_start=166
  _globals['_DEVICECOMMONCAPABILITY']._serialized_end=596
# @@protoc_insertion_point(module_scope)
