# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/hub_rfm.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'systems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/hub_rfm.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nMsystems/ajax/api/ecosystem/v2/hubsvc/commonmodels/device/common/hub_rfm.proto\x12?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common*\x81\x01\n\x06HubRfm\x12\x17\n\x13HUB_RFM_UNSPECIFIED\x10\x00\x12\x0e\n\nHUB_RFM_EU\x10\x01\x12\x0e\n\nHUB_RFM_AU\x10\x02\x12\x0e\n\nHUB_RFM_MA\x10\x03\x12\x0e\n\nHUB_RFM_NA\x10\x04\x12\x0e\n\nHUB_RFM_IN\x10\x05\x12\x0e\n\nHUB_RFM_SA\x10\x06\x42\x46\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.common.hub_rfm_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n?systems.ajax.api.ecosystem.v2.hubsvc.commonmodels.device.commonP\001\272\002\000'
  _globals['_HUBRFM']._serialized_start=147
  _globals['_HUBRFM']._serialized_end=276
# @@protoc_insertion_point(module_scope)
