# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/find_audio_files_for_audio_scenarios/endpoint.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/service/find_audio_files_for_audio_scenarios/endpoint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.v3.mobilegwsvc.service.find_audio_files_for_audio_scenarios import request_pb2 as v3_dot_mobilegwsvc_dot_service_dot_find__audio__files__for__audio__scenarios_dot_request__pb2
from custom_components.ajax.v3.mobilegwsvc.service.find_audio_files_for_audio_scenarios import response_pb2 as v3_dot_mobilegwsvc_dot_service_dot_find__audio__files__for__audio__scenarios_dot_response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nJv3/mobilegwsvc/service/find_audio_files_for_audio_scenarios/endpoint.proto\x12Vsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.find_audio_files_for_audio_scenarios\x1aIv3/mobilegwsvc/service/find_audio_files_for_audio_scenarios/request.proto\x1aJv3/mobilegwsvc/service/find_audio_files_for_audio_scenarios/response.proto2\xb5\x02\n&FindAudioFilesForAudioScenariosService\x12\x8a\x02\n\x07\x65xecute\x12~.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.find_audio_files_for_audio_scenarios.FindAudioFilesForAudioScenariosRequest\x1a\x7f.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.find_audio_files_for_audio_scenarios.FindAudioFilesForAudioScenariosResponseB]\nVsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.find_audio_files_for_audio_scenariosP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.find_audio_files_for_audio_scenarios.endpoint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nVsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.find_audio_files_for_audio_scenariosP\001\272\002\000'
  _globals['_FINDAUDIOFILESFORAUDIOSCENARIOSSERVICE']._serialized_start=318
  _globals['_FINDAUDIOFILESFORAUDIOSCENARIOSSERVICE']._serialized_end=627
# @@protoc_insertion_point(module_scope)
