# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/commonmodels/accounting/available_extra_service.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/commonmodels/accounting/available_extra_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.mobile.v2.common.accounting import accounting_company_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_common_dot_accounting_dot_accounting__company__pb2
from custom_components.ajax.v3.mobilegwsvc.commonmodels.accounting import enriched_target_info_pb2 as v3_dot_mobilegwsvc_dot_commonmodels_dot_accounting_dot_enriched__target__info__pb2
from custom_components.ajax.v3.mobilegwsvc.commonmodels.accounting import service_pb2 as v3_dot_mobilegwsvc_dot_commonmodels_dot_accounting_dot_service__pb2
from custom_components.ajax.v3.mobilegwsvc.commonmodels.accounting import reseller_pb2 as v3_dot_mobilegwsvc_dot_commonmodels_dot_accounting_dot_reseller__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nDv3/mobilegwsvc/commonmodels/accounting/available_extra_service.proto\x12\x41systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.accounting\x1a\x45systems/ajax/api/mobile/v2/common/accounting/accounting_company.proto\x1a\x41v3/mobilegwsvc/commonmodels/accounting/enriched_target_info.proto\x1a\x34v3/mobilegwsvc/commonmodels/accounting/service.proto\x1a\x35v3/mobilegwsvc/commonmodels/accounting/reseller.proto\"\xa6\x03\n\x15\x41vailableExtraService\x12[\n\x07service\x18\x01 \x01(\x0b\x32J.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.accounting.Service\x12V\n\tresellers\x18\x02 \x03(\x0b\x32?.systems.ajax.api.mobile.v2.common.accounting.AccountingCompanyB\x02\x18\x01\x12s\n\x14\x66\x65\x61ture_target_infos\x18\x03 \x03(\x0b\x32U.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.accounting.EnrichedTargetInfo\x12\x63\n\x0ereseller_infos\x18\x04 \x03(\x0b\x32K.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.accounting.ResellerBH\nAsystems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.accountingP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.commonmodels.accounting.available_extra_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nAsystems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.accountingP\001\272\002\000'
  _globals['_AVAILABLEEXTRASERVICE'].fields_by_name['resellers']._loaded_options = None
  _globals['_AVAILABLEEXTRASERVICE'].fields_by_name['resellers']._serialized_options = b'\030\001'
  _globals['_AVAILABLEEXTRASERVICE']._serialized_start=387
  _globals['_AVAILABLEEXTRASERVICE']._serialized_end=809
# @@protoc_insertion_point(module_scope)
