from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class ServiceSwitchAvailabilityStatus(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    SERVICE_SWITCH_AVAILABILITY_STATUS_UNSPECIFIED: _ClassVar[ServiceSwitchAvailabilityStatus]
    SERVICE_SWITCH_AVAILABILITY_STATUS_AVAILABLE: _ClassVar[ServiceSwitchAvailabilityStatus]
    SERVICE_SWITCH_AVAILABILITY_STATUS_UNAVAILABLE: _ClassVar[ServiceSwitchAvailabilityStatus]
SERVICE_SWITCH_AVAILABILITY_STATUS_UNSPECIFIED: ServiceSwitchAvailabilityStatus
SERVICE_SWITCH_AVAILABILITY_STATUS_AVAILABLE: ServiceSwitchAvailabilityStatus
SERVICE_SWITCH_AVAILABILITY_STATUS_UNAVAILABLE: ServiceSwitchAvailabilityStatus
