# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/commonmodels/accounting/subscription_owner.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'v3/mobilegwsvc/commonmodels/accounting/subscription_owner.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.systems.ajax.api.mobile.v2.common.accounting import accounting_company_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_common_dot_accounting_dot_accounting__company__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.common.image import image_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_common_dot_image_dot_image__pb2
from custom_components.ajax.v3.mobilegwsvc.commonmodels.type import user_role_pb2 as v3_dot_mobilegwsvc_dot_commonmodels_dot_type_dot_user__role__pb2
from custom_components.ajax.systems.ajax.api.mobile.v2.hubobject.model.company import company_info_pb2 as systems_dot_ajax_dot_api_dot_mobile_dot_v2_dot_hubobject_dot_model_dot_company_dot_company__info__pb2
from custom_components.ajax.systems.ajax.logging.proto import formatting_options_pb2 as systems_dot_ajax_dot_logging_dot_proto_dot_formatting__options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n?v3/mobilegwsvc/commonmodels/accounting/subscription_owner.proto\x12\x41systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.accounting\x1a\x45systems/ajax/api/mobile/v2/common/accounting/accounting_company.proto\x1a\x33systems/ajax/api/mobile/v2/common/image/image.proto\x1a\x30v3/mobilegwsvc/commonmodels/type/user_role.proto\x1a\x45systems/ajax/api/mobile/v2/hubobject/model/company/company_info.proto\x1a\x33systems/ajax/logging/proto/formatting_options.proto\"\xa4\x04\n\x11SubscriptionOwner\x12i\n\x04user\x18\x01 \x01(\x0b\x32Y.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.accounting.SubscriptionOwner.UserH\x00\x12R\n\x07\x63ompany\x18\x02 \x01(\x0b\x32?.systems.ajax.api.mobile.v2.hubobject.model.company.CompanyInfoH\x00\x12]\n\x12\x61\x63\x63ounting_company\x18\x03 \x01(\x0b\x32?.systems.ajax.api.mobile.v2.common.accounting.AccountingCompanyH\x00\x1a\xe7\x01\n\x04User\x12\x13\n\x0buser_hex_id\x18\x01 \x01(\t\x12\x17\n\nfirst_name\x18\x02 \x01(\tB\x03\xf8\x44\x01\x12\x16\n\tlast_name\x18\x03 \x01(\tB\x03\xf8\x44\x01\x12?\n\x06images\x18\x04 \x01(\x0b\x32/.systems.ajax.api.mobile.v2.common.image.Images\x12X\n\tuser_role\x18\x05 \x01(\x0e\x32\x45.systems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.type.UserRoleB\x07\n\x05ownerBH\nAsystems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.accountingP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.commonmodels.accounting.subscription_owner_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nAsystems.ajax.api.ecosystem.v3.mobilegwsvc.commonmodels.accountingP\001\272\002\000'
  _globals['_SUBSCRIPTIONOWNER_USER'].fields_by_name['first_name']._loaded_options = None
  _globals['_SUBSCRIPTIONOWNER_USER'].fields_by_name['first_name']._serialized_options = b'\370D\001'
  _globals['_SUBSCRIPTIONOWNER_USER'].fields_by_name['last_name']._loaded_options = None
  _globals['_SUBSCRIPTIONOWNER_USER'].fields_by_name['last_name']._serialized_options = b'\370D\001'
  _globals['_SUBSCRIPTIONOWNER']._serialized_start=433
  _globals['_SUBSCRIPTIONOWNER']._serialized_end=981
  _globals['_SUBSCRIPTIONOWNER_USER']._serialized_start=741
  _globals['_SUBSCRIPTIONOWNER_USER']._serialized_end=972
# @@protoc_insertion_point(module_scope)
