from google.protobuf import empty_pb2 as _empty_pb2
from v1.responsible_person import stream_responsible_persons_request_pb2 as _stream_responsible_persons_request_pb2
from v1.responsible_person import stream_responsible_persons_response_pb2 as _stream_responsible_persons_response_pb2
from v1.responsible_person import create_responsible_person_request_pb2 as _create_responsible_person_request_pb2
from v1.responsible_person import create_responsible_person_response_pb2 as _create_responsible_person_response_pb2
from v1.responsible_person import delete_responsible_person_request_pb2 as _delete_responsible_person_request_pb2
from v1.responsible_person import update_responsible_person_request_pb2 as _update_responsible_person_request_pb2
from v1.responsible_person import update_responsible_person_response_pb2 as _update_responsible_person_response_pb2
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor
