# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: v3/mobilegwsvc/service/stream_hub_device/endpoint.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'v3/mobilegwsvc/service/stream_hub_device/endpoint.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from custom_components.ajax.v3.mobilegwsvc.service.stream_hub_device import request_pb2 as v3_dot_mobilegwsvc_dot_service_dot_stream__hub__device_dot_request__pb2
from custom_components.ajax.v3.mobilegwsvc.service.stream_hub_device import response_pb2 as v3_dot_mobilegwsvc_dot_service_dot_stream__hub__device_dot_response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7v3/mobilegwsvc/service/stream_hub_device/endpoint.proto\x12\x43systems.ajax.api.ecosystem.v3.mobilegwsvc.service.stream_hub_device\x1a\x36v3/mobilegwsvc/service/stream_hub_device/request.proto\x1a\x37v3/mobilegwsvc/service/stream_hub_device/response.proto2\xe1\x01\n\x16StreamHubDeviceService\x12\xc6\x01\n\x07\x65xecute\x12[.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.stream_hub_device.StreamHubDeviceRequest\x1a\\.systems.ajax.api.ecosystem.v3.mobilegwsvc.service.stream_hub_device.StreamHubDeviceResponse0\x01\x42J\nCsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.stream_hub_deviceP\x01\xba\x02\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.mobilegwsvc.service.stream_hub_device.endpoint_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\nCsystems.ajax.api.ecosystem.v3.mobilegwsvc.service.stream_hub_deviceP\001\272\002\000'
  _globals['_STREAMHUBDEVICESERVICE']._serialized_start=242
  _globals['_STREAMHUBDEVICESERVICE']._serialized_end=467
# @@protoc_insertion_point(module_scope)
